### ISSUE TITLE
`E5108: col value outside range` when executing `:HopLineAC` on empty line

### ISSUE THREAD

**Issue by mars90226** [phaazon/hop.nvim#100]
When executing `:HopLineAC` on empty line, `E5108: col value outside range` shows up. 
Error shows that the error is at `lua/hop/hint.lua:345` which is
```
        vim.api.nvim_buf_set_extmark(0, hl_ns, hint.line, hint.col - 1, { virt_text = { { hint.hint, "HopNextKey" } }; virt_text_pos = 'overlay' })
```
Since it's empty line, `hint.col - 1` is out of range.

**Comment by phaazon** [comment]
Should be fixed by now. Feel free to update.

**Comment by mars90226** [comment]
It's fixed now, thanks!
