### ISSUE TITLE
Can `HopLine` pick the first non-space character in every line instead?

### ISSUE THREAD

**Issue by iago-lito** [phaazon/hop.nvim#106]
When navigating with `HopLine` within:
```
some file:
   with_say {
         indented_lines

         like this
   }
etc..
```
`HopLine` offers jumping to those locations:
```
Aome file:
B  with_say {
C        indented_lines
D
E        like this
F  }
Gtc..
```
But I would rather jump to these locations instead:
```
Aome file:
   Bith_say {
         Cndented_lines
         D
         Eike this
   F
Gtc..
```
.. is that already possible, or is it something to feature next ? :)

**Comment by phaazon** [comment]
It is probably very easy to implement with the current codebase. It’s just the matter of implementing a `one-shot` hint mode that maps to the first non-whitespace character. However, for your `D`, I don’t think that’s currently easy to do without introducing a state in the hint mode.

**Comment by phaazon** [comment]
Thank for taking the time to making that PR @iago-lito! Great job there. :)
