### ISSUE TITLE
Support configure color of keys?

### ISSUE THREAD

**Issue by xaljer** [phaazon/hop.nvim#107]
color of keys are white in my environment, which is not clearly visible.

**Comment by jlesquembre** [comment]
Same for me, after updating to the latest neovim and hop.nvim, the keys are white. Before they were like in the readme screenshots. But I'm not sure about what changed

**Comment by iago-lito** [comment]
Just in case, have you explicitly linked the corresponding color group ? Like with
```vimscript
hi link HopNextKey WarningMsg
```

This is described in `:help hop-highlights`.

**Comment by jlesquembre** [comment]
I see, now I have to call 
```
require'hop.highlight'.insert_highlights()
```
manually, and it works again as before. I didn't notice that change

**Comment by phaazon** [comment]
You need to call `setup`. It’s done for you automatically. I’m going to have a look at the doc, it should be mentioned somewhere.

**Comment by jlesquembre** [comment]
thanks @phaazon , I missed it. And also thanks for hop.nvim it is a great plugin!
