### ISSUE TITLE
The plugin leaves many [Scratch] buffers

### ISSUE THREAD

**Issue by voldikss** [phaazon/hop.nvim#11]
After using `HopWords` several times, I found there are some `[Scratch]` buffers using `:ls!`.

![hop1](https://user-images.githubusercontent.com/20282795/108061947-0bc71800-7094-11eb-9975-dfc29554620b.gif)

**Comment by phaazon** [comment]
Ah, good catch. That should be easy to fix, thanks!

**Comment by voldikss** [comment]
I am planning to create a PR for the three issues. Would you considerate reviewing it?

**Comment by phaazon** [comment]
You don’t have to do it for the Scratch buffers, but I will review the others, yes!

**Comment by voldikss** [comment]
I'll rebase it.
