### ISSUE TITLE
The searching result isn't apparent 

### ISSUE THREAD

**Issue by jeffersonchen-tw** [phaazon/hop.nvim#115]
Hop didn't dim the text in the buffer.
<img width="1440" alt="截圖 2021-07-01 下午3 47 05" src="https://user-images.githubusercontent.com/67701545/124086758-f3c0c580-da83-11eb-91d6-f38458743794.png">

**Comment by premell** [comment]
I have the same issue

**Comment by gregd** [comment]
Any suggestion how this can be fixed? Some time ago this worked beautifully and now it is hard to distinguish Hop characters from my text characters.

**Comment by jeffersonchen-tw** [comment]
> Any suggestion how this can be fixed? Some time ago this worked beautifully and now it is hard to distinguish Hop characters from my text characters. 
I simply fix it by adding: 

require('hop').setup({create_hl_autocmd = true})

**Comment by premell** [comment]
@jeffersonchen-tw  This worked thank you so much ! How did you figure it out?

**Comment by jeffersonchen-tw** [comment]
@premell I just browse through the source code, and fortunately found this.

**Comment by gegoune** [comment]
http://localhost/#installation

Just running setup should be enough.

**Comment by phaazon** [comment]
Please read the README.

**Comment by phaazon** [comment]
Also, just for posterity for anyone reading this after searching for it in the issues (I hope people do search issues?): `require'hop'.setup()` is enough, no need to pass `create_hl_autocmd`. In doubt, I spent lots of time and deploy long efforts to write a decent Hop documentation, so please use it, everything is explained there. `:h hop`.
