### ISSUE TITLE
Feature: Hop to Treesitter Query / Custom Hop Location Function?

### ISSUE THREAD

**Issue by dlants** [phaazon/hop.nvim#116]
It would be cool to be able to hop to a treesitter matching group, like https://github.com/nvim-treesitter/nvim-treesitter-textobjects ... Then you could "hop to a function" or "hop to a declaration" or "hop to an argument", etc...

Alternately, maybe there could be support for custom location lists? Like a function that could return a list of buffer positions where you could then hint.

Thanks for a great project!

**Comment by mfussenegger** [comment]
I was just going to create a new issue to ask if there's interesting in adding a feature like this.

I prototyped something like that and because a few people liked it I turned it into a plugin (https://github.com/mfussenegger/nvim-ts-hint-textobject) - but I was wondering if it would actually fit into the scope of hop.nvim

The code is fairly simplistic and doesn't deal with a lot of stuff that hop solves (like refining the hint keys). (and the query logic is currently even wrong)

One difference is that it focuses on selecting ranges, but maybe it could be made to support both (either jumping to the start, or selecting the range of a node)

**Comment by phaazon** [comment]
It looks like you’re asking several things at the same time.

A treesitter hint mode can be interesting to add, even though it might be challenging to write given the current code is scoped to the visual part of the buffer in the window. Also, I’m wondering about the usefulness of the idea. I fail to see how people would think « Hey, I want to jump here, and this is… is… a condtional, so I’m going to type something completely different than the regular “hop to word” keybinding. » Jumping to a specific function can already be done with plugins such as fzf, telescope, etc. and I’m not sure about how much people want to “jump to all visible functions.”

For the second part of what you’re asking, I don’t see the relationship between hints and hopping and location lists. But if you want a hinting mode that would do the hinting for all provided buffer positions, then this should be rather simple to do, yes. Even though it would completely cancel the hint mode abstraction and would require the user to do all the (super boring and error-prone) computations to know which buffer positions are visible.

**Comment by dlants** [comment]
For the first point, https://github.com/nvim-treesitter/nvim-treesitter-textobjects implements movements to the "next" or "previous" parameter / function / etc. I think extending this with a "hop to function" is similar as extending a "w" movement to a "hopword".

I think also, something like :HopIdentifier would be interesting. I think in many cases it's actually what users intend when they "hopword". So for example, in CSS "a-class-name" is a single identifier, where in general vim considers a dash a word separator.

> « Hey, I want to jump here, and this is… is… a condtional, so I’m going to type something completely different than the regular “hop to word” keybinding. »

I think If `<leader>w` invokes `:HopWord` and `<leader>j` invokes `:HopLine`, then it's reasonable to make `<leader>i` hop to an identifier, or `<leader>f` to a function definition.

---

On the second point, I now realize, the "location list" is an overloaded term, apologies for being confusing.

I was thinking more in terms of implementation details. Right now the plugin grabs individual lines from the buffer and passes them into the `match` function for each hint mode. I think instead, you could have each mode implement something like `get_hop_targets` function, which would return a list of places to jump to. Then you could use methods other than scanning line-by-line to generate that list, like querying treesitter. I was thinking that people could also potentially implement their own custom hint modes by supplying their own `get_hop_targets` function.

**Comment by phaazon** [comment]
Yeah, I get what you mean with the second point and I agree, it would allow people to extend Hop on their side and contribute probably more. For `:HopIdentifier`, that’s probably a good point as well. :)

**Comment by phaazon** [comment]
So, the second point is now a thing and it’s possible to write _Hop extension plugins_. See `:h hop-extension`. For the first point about Treesitter, this is not something that goes into the direction Hop should go, but you are free to implement a Hop extension implementing it. I will be happy to list the extensions in a place like e.g. a wiki on the GitHub page.
