### ISSUE TITLE
Treesitter features

### ISSUE THREAD

**Issue by premell** [phaazon/hop.nvim#118]
It would be cool to highlight words based on what kind of word it is, like make functions yellow and variables green or something. Could maybe follow the currently used colorscheme. You could also make it so that the first of the two letters are always the same on the same types of words. For instance all functions could start with "f", like "fd", "fj", "fk", and all variables could start with "g". 

But I have no idea how hard this is to implement

**Comment by phaazon** [comment]
Sorry but this is not in the scope of Hop as it would be more distracting than useful. The idea to use a `f` as starting key would make Hop much less performant in terms of average number of keys to press.

You might want to have a look at #116 for the rest of your questions but it’s unlikely to be supported short-term.

**Comment by premell** [comment]
> Sorry but this is not in the scope of Hop as it would be more distracting than useful. The idea to use a `f` as starting key would make Hop much less performant in terms of average number of keys to press.
> 
> You might want to have a look at #116 for the rest of your questions but it’s unlikely to be supported short-term.

I didn't mean it should take more keys, just that the keys are more consistent. If all variables starts with "g" you can build up some kind of muscle memory.  I meant like "gv", "gj" etc instead of the first letter being random.  Still 2 letters
