### ISSUE TITLE
Incorrect hop floating window position when 'virtualedit` is empty

### ISSUE THREAD

**Issue by voldikss** [phaazon/hop.nvim#12]
![hop2](https://user-images.githubusercontent.com/20282795/108062505-d969ea80-7094-11eb-9834-01c106f00f8e.gif)

**Comment by phaazon** [comment]
Hm, that’s very interesting. I’ve never planned anything around `virtualedit`. I’ll look into it!

**Comment by voldikss** [comment]
I've create a patch in which I set `virtualedit` to `all`, and restore it after opening the hop floating window.
