### ISSUE TITLE
Help: operator motion & highlight examples

### ISSUE THREAD

**Issue by spamwax** [phaazon/hop.nvim#121]
I am new to Lua-based plugins so this may seem trivial to most of Hop users, but...
How do I configure Hop to work with operator motions (`d`, `c`, ...)? 
Also how do you change the highlight of the target keys? in the help file I see the "HopNextKey" and ... but cannot figure out how to change the highlights.

Is it possible to update the readme file or add a Wiki page for more examples of customization?

**Comment by hiberabyss** [comment]
I use following map which could work with operation.

```
map <silent> <Space>w <Cmd>HopWordAC<cr>
```

**Comment by will** [comment]
I've set it up like this

```
  {
    "phaazon/hop.nvim",
    event = "BufRead",
    config = function()
      require("hop").setup()
      vim.api.nvim_set_keymap("n", "s", ":HopChar2<cr>", { silent = true })
      vim.api.nvim_set_keymap("n", "S", ":HopWord<cr>", { silent = true })
    end,
  },
```

and it'd be nice if I could do something to get `ds` or `dS` to work too, but I haven't been able to figure it out yet.

**Comment by spamwax** [comment]
Thanks all,

I am also using something similar

```lua
vim.api.nvim_set_keymap('v', 't', "<cmd>lua require'hop'.hint_char1()<cr>", {noremap=true})
```

Still haven't figured out how to change colors.

**Comment by partiallyordered** [comment]
For `ds` (in this example `df`) and similar I have:
```lua
vim.api.nvim_set_keymap('n', 'f', "<cmd>lua require'hop'.hint_char1()<cr>", {})
vim.api.nvim_set_keymap('x', 'f', "<cmd>lua require'hop'.hint_char1()<cr>", {})
local actions = { "d", "c", "<", ">", "y" }
for _, a in ipairs(actions) do
    vim.api.nvim_set_keymap('n', a .. 'f', a .. "<cmd>lua require'hop'.hint_char1()<cr>", {})
    vim.api.nvim_set_keymap('x', a .. 'f', a .. "<cmd>lua require'hop'.hint_char1()<cr>", {})
end
```

**Comment by phaazon** [comment]
Passing `n` will work only for normal mode. You want to use the empty string here.
