### ISSUE TITLE
Support for a feature like let g:EasyMotion_do_shade = 0?

### ISSUE THREAD

**Issue by gkapfham** [phaazon/hop.nvim#129]
Hello, I really like the hop.nvim plugin and I appreciate all of your efforts in developing, documenting, and maintaining it. I've been using EasyMotion for a long time and I am considering a switch for exactly the reasons mentioned in the README.

When I use EasyMotion I always set `let g:EasyMotion_do_shade = 0` so that the background and the text are not shaded but kept at their standard color and brightness. This is because of the fact that I find the color changes jarring and, more importantly, my eyes often cannot easily see the word that I want when the "shade" is introduced.

I checked the documentation and I see `HopNextKey` and the three other parameters. Is there a way to control the shading in hop.nvim or to disable the shading entirely? Thanks for any feedback or efforts that you can provide in this regard. Finally, if there is a way to control the shade as you can in EasyMotion and I overlooked it please accept my apology and, if possible, point me in the right direction.

**Comment by bushblade** [comment]
I came here to make the exact same feature request, so plus one on this please.

**Comment by xeluxee** [comment]
If I understand correctly what you mean you can try this:
``` vim
:hi HopUnmatched gui=none guifg=none guibg=none
```

**Comment by gkapfham** [comment]
Since it seems as though there is a viable solution to this issue, I am going to close it.

**Comment by userrand** [comment]
> If I understand correctly what you mean you can try this:
> 
> ```viml
> :hi HopUnmatched gui=none guifg=none guibg=none
> ```

How can one add that to their vimrc? There seems to be an issue with adding highlight commands in a vimrc file according to https://vi.stackexchange.com/questions/10035/how-can-i-make-highlighting-commands-in-vimrc-take-effect-immediately-with-vim
