### ISSUE TITLE
Feature Request: Current-line only hopping

### ISSUE THREAD

**Issue by spamwax** [phaazon/hop.nvim#134]
It's a very common workflow to want to change/delete up to a character just within the same line.
Right now Hop shows possible jumps in all of the window which can be quite distracting, and takes away the key shortcuts that may prove to be useful.

So maybe having something that just focuses on current line and shows the possible candidates by just highlight/re-coloring the current line would be a nice addition.

**Comment by michielappelman** [comment]
This is an existing request as described in #91
