### ISSUE TITLE
Feature Request - `HopCharAuto` based on chars occurrences count

### ISSUE THREAD

**Issue by zhengpd** [phaazon/hop.nvim#135]
The idea is to have a `HopCharAuto` command to call `HopChar1` if user-typed char occurs less than N times (e.g. 26), otherwise `HopChar2`. The reason is, you might not want to type 2 chars if 1-char mode allows to jump to the target position quickly.

My vimscript workaround, for reference:

```vim
function! CountStringInScreen(str)
  let screen_lines = getbufline(bufnr('%'), line('w0'), line('w$'))
  return count(join(screen_lines), a:str, 1)
endfunction

function! HopCharAuto()
  let char1 = nr2char(getchar())
  if CountStringInScreen(char1) < 26
    call feedkeys(char1) | HopChar1
  else
    let char2 = nr2char(getchar())
    call feedkeys(char1.char2) | HopChar2
  endif
endfunction
nmap <silent> s :call HopCharAuto()<cr>
```

**Comment by phaazon** [comment]
Interesting concept. I’m not willing to give it a try _for now_ but I would probably accept a PR adding this.

**Comment by zhengpd** [comment]
I don't use the `HopCharAuto` anymore because it causes unpredictable and inconsistent key presses (sometimes 2, sometime 3) which slows down jumping. I'll close this issue.
