### ISSUE TITLE
Feature Request: best suggestion

### ISSUE THREAD

**Issue by ayoubelmhamdi** [phaazon/hop.nvim#137]
if i have this text
```
foo ffoo
bar bbar
```
then i use `:HopChar1` , text will be change to:
![hop1](https://user-images.githubusercontent.com/34358145/128650584-36c13eac-3aab-4ad9-a869-a318b45d12c8.png)
but , the best suggestion is the next char  as possible  `o and f`  
![hop3-psd](https://user-images.githubusercontent.com/34358145/128651322-19ae22d5-594e-4e6b-9f4e-25291a478f7a.png)

**Comment by phaazon** [comment]
Sorry, I don’t understand your need. Feel free to comment to explain a bit more what you have on your mind and I’ll re-open.

**Comment by ayoubelmhamdi** [comment]
i found new plugin called lightspead do this job
