### ISSUE TITLE
Hop with delay

### ISSUE THREAD

**Issue by adelin-b** [phaazon/hop.nvim#141]
There is this awesome variant on emacs where you can 
- :HopDelay
- type N char and when you didnt typed anything for 500ms 
- move cursor if alone / show hints

Its fabulous

**Comment by phaazon** [comment]
This is not currently planned as it would completely defy the goal of Hop (jumping fast). However, it is possible to implement that behavior with a Hop extension and using the Hop Lua API to debounce all the commands (`hop.hint_words` is just `hop.hint_with` with the right generator; all of that is documented in the help pages).
