### ISSUE TITLE
When using HopChar2, fallback to HopChar1 if only 1 character is entered.

### ISSUE THREAD

**Issue by Corey-Keller** [phaazon/hop.nvim#142]
With EasyMotion, when I use the `<Plug>(easymotion-s2)` command and enter just a single character, and use the enter/return key to continue it falls back to `<Plug>(easymotion-s1)` behavior, which is the desired result.

I'm not sure if this is a feature request, or a bug (which I'd assume it'd be a bug if the goal is to function the same as EasyMotion)

**Comment by glyh** [comment]
It's seem like we already have this behavoir, for example you like to match "a", in 2 char mode, type "a*", you can match it.

**Comment by phaazon** [comment]
That has been supported for a couple of months now and I forgot to link to this issue. Thank you for reporting.
