### ISSUE TITLE
Strange behavoir of "*" at the end of line in find 2 char function when line is too long 

### ISSUE THREAD

**Issue by glyh** [phaazon/hop.nvim#143]
To reproduce: 
- type a long line without '\n' or '\r', start with "abc", end with "a*m*"
- Call hop to find 2 chars.
- Type "m*"
- Hop panic that it can't find any match
- Call hop to find 2 chars.
- Type "a*"
- Hop found at the head of line
- Hop panic that it can't find any match. 

[![asciicast](https://asciinema.org/a/H7ib6dLR6uZCEVCut5gGglKqh.svg)](https://asciinema.org/a/H7ib6dLR6uZCEVCut5gGglKqh)

**Comment by phaazon** [comment]
I don’t reproduce anymore.
