### ISSUE TITLE
Feature Request: JumpToAnywhere

### ISSUE THREAD

**Issue by guilhermeprokisch** [phaazon/hop.nvim#144]
In Easymotion there's the function JumpToAnywhere. There are any plans to also implement in hop?

https://github.com/easymotion/vim-easymotion/blob/d75d9591e415652b25d9e0a3669355550325263d/doc/easymotion.txt#L341

**Comment by ELLIOTTCABLE** [comment]
I'm pretty sure you can implement this yourself using `hop.hint_patterns()`; but I agree that including a pre-baked snippet in the documentation for switching users searching for "anywhere" is a good idea.

**Comment by phaazon** [comment]
Oh that should be very easy to add, yes. Feel free to open a PR! There is already everything needed to implement that. Look at how `hint_words` is implemented in `init.lua`. :)

**Comment by rosshadden** [comment]
Combining the advice above from everybody, this is the result that I ended up using:

```lua
vim.keymap.set("n", "-a", function()
	hop.hint_patterns({}, [[\v(<.|^$)|(.>|^$)|(\l)\zs(\u)|(_\zs.)|(#\zs.)]])
end, { silent = true, noremap = true })
```

> Note: "-" on dvorak is my ' key and very easy to reach, so don't make fun of me for using a weird faraway mapping haha
