### ISSUE TITLE
No keyword mode

### ISSUE THREAD

**Issue by s1n7ax** [phaazon/hop.nvim#145]
Option to skip all the keywords and only jump to user-inputs like function name, class name etc.

For instance, in following java class, only include `DemoApplication`,  `main`,  `args`,  `hello world`.

```java
public class DemoApplication {
    public static void main(String[] args) {
        System.out.println("hello world");
    }
}
```

I think it is better to add errors in `treesitter` language tree also to jump list.

**Comment by phaazon** [comment]
I think you can implement that with either a plugin (there is a tree-sitter extension plugin for Hop somewhere), or simply change the regex. `:h hop` have that kind of information.
