### ISSUE TITLE
Can't configure highlight colors

### ISSUE THREAD

**Issue by pawelchabros** [phaazon/hop.nvim#149]
Hi. Thank you for great plugin!

I'm trying to change highlight colors. Both

```
hi HopNextKey guifg=#b48ead
hi HopNextKey1 guifg=#b48ead
hi HopNextKey2 guifg=#b48ead
hi HopUnmatched guifg=#e5e9f0
```

and

```
require'hop'.setup {
  HopNextKey = '#b48ead',
  HopNextKey1 = '#b48ead',
  HopNextKey2 = '#b48ead',
  HopUnmatched = '#e5e9f0'
}
```

doesn't work.

**Comment by phaazon** [comment]
`:h hop-highlights` should help you with that. If you want to change the default highlight, you need to make Hop not insert auto-command and initialize the highlights by yourself.
