### ISSUE TITLE
Incorrect hints position for lines that has tabs in help buffer

### ISSUE THREAD

**Issue by voldikss** [phaazon/hop.nvim#15]
There seems a lot problems with help buffer...

See the gif below

![hop4](https://user-images.githubusercontent.com/20282795/108080175-8a2eb480-70aa-11eb-9127-35b24597c13e.gif)

The hints for the 3rd line (also other lines in gif) is wrong. These lines have a `\t` whose length equals `&tabstop` value.

I've fixed this by substitube all `\t` with `string.rep(' ', tabstop)`. Don't know whether it's a proper fix...

```patch
diff --git a/lua/hop/hint.lua b/lua/hop/hint.lua
index a35d95e..855cb81 100644
--- a/lua/hop/hint.lua
+++ b/lua/hop/hint.lua
@@ -79,6 +79,9 @@ function M.mark_hints_line(hint_mode, line_nr, line, col_offset, buf_width)
     end_index = vim.fn.strdisplaywidth(line)
   end
 
+  -- local tabstop = vim.api.nvim_buf_get_option(0, 'tabstop')
+  -- line = line:gsub("\t", string.rep(' ', tabstop))
+
   local shifted_line = line:sub(1 + col_offset, end_index)
 
   -- prevent empty lines from being really empty; useful for some modes
```

**Comment by phaazon** [comment]
Yes, if you’re using tabs, the current implementation really misbehave. Your implementation seems fine for now to me, but I want to revamp that code at some point when taking care of the emoji multi-byte issue.

Thanks a lot!

**Comment by phaazon** [comment]
I made a fix for this. Testing and pushing today.
