### ISSUE TITLE
HopUnmatched not being applied when using certain language servers

### ISSUE THREAD

**Issue by RononDex** [phaazon/hop.nvim#150]
This is related to https://github.com/phaazon/hop.nvim/pull/62 

I just ran into the same issue, did a short analysis and found out the following:
- On my setup it only happens when I open a C# project (which uses coc-omnisharp)
- First it works fine, but then stops working after the language server loaded
- Omnisharp replaces some highlighting groups in the buffer, to support code highlighting in C#
- It works fine with coc-java for example

So to reproduce the issue, just open a C# project (for example https://github.com/RononDex/FitsLibrary) with coc-omnisharp installed, then try to use a hop command.

![2021-09-19_17-13](https://user-images.githubusercontent.com/2249071/133932754-b95f3d14-b80a-4647-b434-6a10b4548aaf.png)

**Comment by phaazon** [comment]
Do you still have that issue? Lots have happened so I’m going to preemptively close this, but don’t hesitate to comment again if you still have the problem so that we can re-open.
