### ISSUE TITLE
How to jump after a colon ; or quote "

### ISSUE THREAD

**Issue by ShivamJoker** [phaazon/hop.nvim#152]
I was wondering what would be the mode for using it like the normal hop ?
Like right now I would like to jump after the colon and delete stuff
normally I would just do `F:` but here it opens up the command mode

![image](https://user-images.githubusercontent.com/23727670/134314484-e145d6cc-c984-45d4-8ad0-e259ddbe960b.png)

**Comment by phaazon** [comment]
You can bind a key to `:HopChar1CurrentLineAC`. See `:h hop`. The [README keybinding section](https://github.com/phaazon/hop.nvim#keybindings) has the exact example you are asking for.
