### ISSUE TITLE
Custom highlights only work after 're-sourcing' init file

### ISSUE THREAD

**Issue by benfrain** [phaazon/hop.nvim#156]
I have this config:

```lua
-- Hop
require("hop").setup()
map("n", "<leader>h", "<cmd>lua require'hop'.hint_words()<cr>")
map("n", "<leader>l", "<cmd>lua require'hop'.hint_lines()<cr>")
map("v", "<leader>h", "<cmd>lua require'hop'.hint_char2()<cr>")
map("v", "<leader>l", "<cmd>lua require'hop'.hint_lines()<cr>")
vim.cmd("hi HopNextKey guifg=#ff9900")
vim.cmd("hi HopNextKey1 guifg=#ff9900"

https://user-images.githubusercontent.com/1318466/137007451-c8686d84-dbd9-4838-b25c-4214a8943d44.mov

)
vim.cmd("hi HopNextKey2 guifg=#ff9900")
```

When I first open nvim and instantiate Hop I get default Hop highlight colors. If I then source the init file again, I get the expected custom ones.

Full init.lua: https://gist.github.com/benfrain/97f2b91087121b2d4ba0dcc4202d252f

https://user-images.githubusercontent.com/1318466/137007485-893b5149-fc0c-42eb-895b-c6eb229f8caf.mov

Is this something I am doing wrong??

**Comment by phaazon** [comment]
`:h hop-highlights`, most specifically the last paragraph:

> Highlights are inserted in an augroup, HopInitHighlight, and an autocommand is automatically set when initializing the plugin, unless you set hop-config-create_hl_autocmd to false.
