### ISSUE TITLE
Hide cursor whilst overlay is active

### ISSUE THREAD

**Issue by akinsho** [phaazon/hop.nvim#16]
So this is *entirely* a visual improvement than a must have, but I've noticed that whilst the overlay is visible it shows the cursor position at the top of the window which is a little distracting, I think it'd be a nice configurable option to hide it. Personally I think it would be a good default but I'm sure there will be differing opinions (/ it wont work if the user isn't using `termguicolors`).

Anyway I looked a little into how this is done `coc.nvim` which hides the cursor in `coc-list` and it pointed towards https://github.com/neovim/neovim/pull/11519 change in neovim. I believe you can capture the initial value of the `&guicursor` change it and just before closing the window return it to it's previous state.

I appreciate this one is a little bit of work for a small visual improvement but figured I'd raise it to see what your thoughts were

**Comment by bew** [comment]
Hmm I think it would make more sense to put the cursor at the same location than the calling buffer

**Comment by phaazon** [comment]
Yes, I had a first implementation leaving the cursor at the same place, but it was erroneous and I think I’m going to fix it. However, it should be easy to have an option to hide it (disabled by default, I think it should be there by default).

**Comment by akinsho** [comment]
Hmm tbh having it stay where it was is actually the better default 😆 I think either would be good, but probably staying in the same place would be what most people expect as they might not understand that it's a window on top of their buffer and why the cursor is suddenly in a different place

**Comment by akinsho** [comment]
Think this isn't relevant any more with the switch to using extmarks so will close this out 👍🏿

**Comment by phaazon** [comment]
Yep, thanks!
