### ISSUE TITLE
can not jump to last character on a line if we use HopChar2

### ISSUE THREAD

**Issue by jdhao** [phaazon/hop.nvim#166]
Since command `HopChar2` requires the user to type two characters to show the hint, I can not seem to jump to the last character on a line because there is no character after it.

I am thinking about if user press a character and then press Enter, then fall back to `HopChar1`?

**Comment by phaazon** [comment]
I never thought about that issue. I think a fix like what you describe would be greatly appreciated! We should probably be able to branch on the second character and test for `\n` or similar, and do not append the second character in that case.

Great idea, will fix soon unless someone provide a patch. :slightly_smiling_face:

**Comment by jdhao** [comment]
if this feature is implemented, it will behave like vim-sneak, where you can switch to one-char search mode if you press a key and then press enter.

**Comment by phaazon** [comment]
Yeah, and that’s probably super simple to fix. I will make a patch about it tonight and release it as a patch bump.
