### ISSUE TITLE
[Feature Request]: use uppercase target labels and type as a lower case

### ISSUE THREAD

**Issue by Mr-Jack82** [phaazon/hop.nvim#167]
The name of the title speaks for itself. Easymotion has the ability to assign an uppercase letter as a target and use a lowercase letter to jump to it. This may be a minor improvement, but IMHO it improves the user experience.

**Comment by ggandor** [comment]
The point of this would be that uppercase letters are more visible?

**Comment by Mr-Jack82** [comment]
Yes of course, it's all about visibility
