### ISSUE TITLE
Incorrect hop window position for floating window

### ISSUE THREAD

**Issue by voldikss** [phaazon/hop.nvim#17]
The `'relative': 'win'` option in `nvim_open_win` seems not workable for floating window.
We should also respect the floating window position using some functions like `nvim_win_get_position()`

![hop](https://user-images.githubusercontent.com/20282795/108158879-d87e9a80-7120-11eb-934f-4931cdc5854f.gif)

**Comment by phaazon** [comment]
I don’t even understand what’s happening in that gif :D But yeah, offsetting everything with the window position shouldn’t be too hard to do.

**Comment by voldikss** [comment]
In the gif, I did the following things:

- open a floating window at the canter position of the editor
- jump to that window
- `:HopWord`
- the hop window was opened at the topleft corner of the whole editor instead of covering the floating window

I've made another minimal vimscript to reproduce the issue, see the following code snippets and the gif

```vim
let options = {
      \ 'relative': 'editor',
      \ 'height': 10,
      \ 'width': 20,
      \ 'row': 20,
      \ 'col': 20,
      \ 'style': 'minimal',
      \ }
call nvim_open_win(0, v:true, options)
```

![hop](https://user-images.githubusercontent.com/20282795/108444059-dc332e00-7294-11eb-8199-7d4e4c866260.gif)

**Comment by phaazon** [comment]
Can you try again and tell me whether it’s still an issue? The recent work, especially since #34, should have fixed that.

**Comment by voldikss** [comment]
The issue got resolved. Thank you so much!
