### ISSUE TITLE
Requests for the new API

### ISSUE THREAD

**Issue by IndianBoy42** [phaazon/hop.nvim#173]
I've been trying to port my fork of hop.nvim (treesitter based targets) to the new API, and I seem to have run into some problems/annoyances

- passing `nil` or `{}` to the opts parameter of hint_with doesn't seem to work. I get an error message 
```
lua/hop/perm.lua:160: attempt to index field 'perm_method' (a nil value)
```
I fixed it by doing this:
```
local function override_opts(opts)
  local hopopts = require("hop").opts
  return setmetatable(opts or {}, {
    -- __index = function(_, key)
    --   return hopopts[key]
    -- end,
    __index = hopopts,
  })
end
```
Basically falling back on the global opts table.

- I have to create the `indirect_jump_targets` even if my only plan is to assign a 0 score to all of the jump targets. It would be nice if not supplying a table there would just assume a score of 0 for all the targets.

- I think if I fill in `indirect_jump_targets` with 0 score for all the targets, then the hint labels are assigned according to the order of targets in `jumps`, am I right? If I want it ordered according to the distance from the users cursor I should use some distance metric for the scores. This seems common enough that I wonder if there should be an easier way of specifying this, and let hop calculate and sort according to distances, rather than plugin writers having to repeat that logic everytime

**Comment by phaazon** [comment]
Interesting points! I will try to address it asap. :)
