### ISSUE TITLE
Do you happen to know if a similar utility exists for tmux :)

### ISSUE THREAD

**Issue by novicebaba** [phaazon/hop.nvim#174]

**Comment by bew** [comment]
What would you want to happen in tmux? AFAIK you can't just jump to anywhere and expect to do something useful, or do you want to jump to a pane? (this already exists in tmux, but with numbers not letters)

**Comment by timtyrrell** [comment]
https://github.com/fcsonline/tmux-thumbs
https://github.com/schasse/tmux-jump

https://github.com/tmux-plugins/list is a good reference
