### ISSUE TITLE
Recent commit causes error

### ISSUE THREAD

**Issue by smackesey** [phaazon/hop.nvim#178]
```
E5108: Error executing lua ...rs/smackesey/.cache/nvimplugin/hop.nvim/lua/hop/init.lua:158: attempt to index field 'diagnostic' (a nil value)
```

This now happens to me when using my usual hop mappings, I suspect related to #157

**Comment by jdhao** [comment]
Same error here. The check in the code is not enough, I am also on the 0.6 branch, but I have not used the bleeding edge nvim. So the `vim.diagnostic` thing does not exist even if I have nvim 0.6.

**Comment by domas-v** [comment]
I get a similar message - same line and error code, but a bit different message
`E5108: Error executing lua ..hare/nvim/site/pack/paqs/start/hop.nvim/init.lua:158: attempt to call field 'get_namespaces' (a nil value)`.
How can I help?

**Comment by jdhao** [comment]
@domas-v  which version of nvim are you using? nvim 0.5.1 works without error for me.

**Comment by bluretrece** [comment]
@domas-v @jdhao exact error here. I'm currently using `nvim v0.6.0-dev+359-g63fde086d`. Is the nightly release supported?

**Comment by jdhao** [comment]
@bluretrece  I think the nightly version is supported, but you have to use the latest nightly, not some nightly version loong time ago.

**Comment by phaazon** [comment]
The joy of that kind of things… I’ll fix it, thanks for the report.

**Comment by phaazon** [comment]
I’m going to add something in the README explaining this.

**Comment by clason** [comment]
Neovim maintainer here with a PSA. Neovim supports exactly two versions:
1. the last release (currently 0.5.1),
2. the **latest** commit on `master` (which currently reports as `0.6`).
In particular, it does _not_ support older commits! If you decide to use the bleeding edge, you **have to** constantly keep it up-to-date with `HEAD` (as well as all plugins).

**Comment by phaazon** [comment]
Thanks for the clarification @clason
