### ISSUE TITLE
[Suggestion] Move two gifs out of the plugin repo for the download speed

### ISSUE THREAD

**Issue by voldikss** [phaazon/hop.nvim#18]
Hi @phaazon it may surprise you to hear that 2M gifs can even slow down the speed of plugin installation. However, it did make the user experience worse sometimes for some people. 

Due to some fxxking unspeakable reasons, the speed of `git clone` in some places of China is terrible. Therefore, note that the size of two gifs accounts for 70% of that of the whole repository, it's better to move those gifs to another places (issue region for example) and fill their links in the README.md. A feasible approach for example, is opening an issue named "screenshot" or "demo" etc for storing gifs.

**Comment by phaazon** [comment]
Ah. You are completely right here. I’ll move them out.
