### ISSUE TITLE
Exceptions in nvim-0.6

### ISSUE THREAD

**Issue by mitchpaulus** [phaazon/hop.nvim#181]
I've been running the latest builds of Neovim 0.6 and ran into exceptions when doing hops. 

In particular, get error:

```
E5108: Error executing lua /dir/to/hop.nvim/lua/hop/init.lua:158: attempt to index field 'diagnostic' (a nil value)
```

Looks like the issue is with special handling for nvim-0.6. Issues occur at lines 157-160 and 227-229 of lua/hop/init.lua.

```lua
  if vim.fn.has("nvim-0.6") == 1 then
    hint_state.diag_ns = vim.diagnostic.get_namespaces()
    for ns in pairs(hint_state.diag_ns) do vim.diagnostic.hide(ns) end
  end
```

```lua
  if vim.fn.has("nvim-0.6") == 1 then
    for ns in pairs(hint_state.diag_ns) do vim.diagnostic.show(ns, buf_handle) end
  end
```

From what I can tell, there is no `vim.diagnostic` namespace in the latest Neovim. Is this supposed to be `vim.api.nvim_get_namespaces` or `vim.lsp.diagnostic.**`?

The exact version I was running was:

`v0.6.0-dev+155-g15b736d6e-dirty`

**Comment by mitchpaulus** [comment]
Sorry, just now saw #178 and #179 and latest README note.

**Comment by phaazon** [comment]
Please use the latest build of neovim if you’re using the nightly release
