### ISSUE TITLE
E5108: end_col value outside range, when virtualedit=all

### ISSUE THREAD

**Issue by iago-lito** [phaazon/hop.nvim#193]
Hello, I often come accross this bug:
- Open a non empty file.
- Ensure that `:set virtualedit=all`.
- Navigate to a non-empty line.
- Navigate past the end of this line (*e.g.* `$l` or `$5l`).
- Attempt to execute `:HopWordBC`

This results in:
```
E5108: Error executing lua /home/iago-lito/.vim/plugged/hop.nvim/lua/hop/init.lua:56: end_col value outside range
```
Is it possible to use Hop seamlessly with `virtualedit=all`?

**Comment by phaazon** [comment]
Just fixed that.
