### ISSUE TITLE
`HopChar2CurrentLine` behave like `HopChar2`

### ISSUE THREAD

**Issue by fitrh** [phaazon/hop.nvim#196]
Or is it the intended behavior ? afaik, the `CurrentLine` means apply jump hint on the current line, the `HopChar1` work as expected

https://user-images.githubusercontent.com/55179750/143837347-da5513a6-683b-4e5e-859c-fbe8954dda76.mp4

**Comment by phaazon** [comment]
Nope you are right, it’s a bug. Thanks for opening the issue.

**Comment by fitrh** [comment]
Fixed by #200 right ?
