### ISSUE TITLE
Consistent jump hints

### ISSUE THREAD

**Issue by mikeslattery** [phaazon/hop.nvim#198]
When I use hop, the jump hints seem randomly ordered.   It would be nice if the first, second, third, forth, etc positions were always the same character hints (respectively as `asdf`), like in EasyMotion.

For example, if I had `f` mapped, and `s` always hinted the 2nd occurance, and I wanted to go to the 2nd occurance of `x` I might type: `fxs`

Hop's random ordering slows me down compared to EasyMotion as I have to wait and read the hints before I jump, and I can't use them in macros.

**Comment by Chaitanyabsprip** [comment]
from what I have experienced and even read about the algorithm that phaazon uses, the second occurence will always be marked with the same key. https://phaazon.net/blog/blog/hop-trie-backtrack-filling.

**Comment by phaazon** [comment]
The article is https://phaazon.net/blog/blog/hop-trie-backtrack-filling. Order is not enforced but will most of the time be an emergent property.

**Comment by bew** [comment]
> The article is https://phaazon.net/blog/blog/hop-trie-backtrack-filling. Order is not enforced but will most of the time be an emergent property.

Note that this URL gives a 404, removing one `blog/` fixes it, but the page seems to rewrite the URL to add the second `blog/` :eyes:

**Comment by mikeslattery** [comment]
[Interesting and helpful article, thank you.](https://phaazon.net/blog/hop-trie-backtrack-filling)  Tbh, when using `:HopChar1*` I'd prefer predictability and consistency over optimal permutation length.   **I want to type *fast* without halting to look at hints** that I can easily predict.  I'd rather use `:HopChar2*` when seeking optimal permutation length.

I'll experiment with restoring the original `perm_method` algorithm (`TermSeqBias`?) for 1-char searches (after switching back to Hop from EasyMotion) and I'll post my thoughts about it here when I'm done.   Although it's [mentioned in the docs](https://github.com/phaazon/hop.nvim/blob/v1.2.0/doc/hop.txt#L586) `TermSeqBias` is [no longer implemented in the source](https://github.com/phaazon/hop.nvim/commit/03f34d5e9fe2c7a81a6aa2e9a46b6ce686cd086f#diff-60a3f0baf37edc61190407bff83f101fb20d8a5d95b2d6bb73633d5d19be7de0).

**Comment by mikeslattery** [comment]
My experiment failed to reliably give hints (in `asdfghkl...` order) when using the original v0.0.1 algorithm.   Turns out, the core of the problem is that `hint.lua` implements the 2D [Manhattan Distance](https://en.wikipedia.org/wiki/Taxicab_geometry) instead of using the 1D/linear file offset as the distance.

A poor workaround is to set `current_line_only = true`, so the 2D distance algo can't take row distance into account.

This may be too big to fix in Hop without a major refactor.  I'm going back to EasyMotion until either someone writes a PR for this issue, or I find the time to write rewrite `hint.lua`.

**Comment by JoannesJ** [comment]
Quick solution would be to crank up the [`x_bias` on the `manh_dist` function](https://github.com/phaazon/hop.nvim/blob/f418a3750ed3a7f321287a39d2c9a56d8ad630aa/lua/hop/jump_target.lua#L52) to a number bigger than any practical line size. Beyond that, I'm not sure if there is any meaningful consistency to be gained.

**Comment by mikeslattery** [comment]
Closing.
I've decided to no longer use `f`/`t`/`F`/`T` mappings of hop.  `s` is king.  Plus, no one else seems interested.

**Comment by yanshay** [comment]
> Closing. I've decided to no longer use `f`/`t`/`F`/`T` mappings of hop. `s` is king. Plus, no one else seems interested.

How does 's' solve this issue for you? It isn't consistent either in my tests.

I'm also looking for a way to record macros, f/s/t are pretty important for that and with Hop such macros are impossible. Is there some alternative (even if less convenient) solution to macros other than not using Hop?

**Comment by mikeslattery** [comment]
FYI, I came to the realization that Hop's design focus doesn't match my goals.

> Hop is an EasyMotion-like plugin allowing you to jump anywhere in a document with as few keystrokes as possible

Fewest keystrokes is not a goal, it's a strategy.  I want speed, which for me means least cognitive load.  I want to move without thinking.  Paying attention to seemingly randomized hints is antithetical to that goal.

**Comment by Chaitanyabsprip** [comment]
what plugin have you replaced hop with? I am interested in your idea of a jump plugin, prioritizing cognitive load over keystrokes makes sense to me.

**Comment by yanshay** [comment]
> Quick solution would be to crank up the [`x_bias` on the `manh_dist` function](https://github.com/phaazon/hop.nvim/blob/f418a3750ed3a7f321287a39d2c9a56d8ad630aa/lua/hop/jump_target.lua#L52) to a number bigger than any practical line size. Beyond that, I'm not sure if there is any meaningful consistency to be gained.

@JoannesJ I tried your suggestion but it didn't work. Changing the x_bias does have an effect but it doesn't generate consistency even on the current line.

**Comment by JoannesJ** [comment]
@yanshay Did you do it with the `direction` option set?

**Comment by yanshay** [comment]
> @yanshay Did you do it with the `direction` option set?

yes

**Comment by mikeslattery** [comment]
@Chaitanyabsprip [Leap](https://github.com/ggandor/leap.nvim)

It's not a bullseye for me, but it's very close.  You use the actual 2 characters at the location, with an optional 3rd char for secondary location hints.   The 3rd is (necessarily) random.  What's nice is you see the 3rd character hint after typing the 1st, so it gives your brain a few milliseconds to process it.  My only wish is that it would use the actual 3rd character at the location when possible, rather than *always* being random.

It's not nearly as keystroke efficient as Hop.  I'd say it takes one extra keystroke over Hop on average.

**Comment by Chaitanyabsprip** [comment]
I have also been using leap, and it takes minimum 3 keystrokes to get anywhere, maybe if leap adopts hop's algo or hop implements the eager hinting then we'll have our sweetspot

**Comment by ggandor** [comment]
> I have also been using leap, and it takes minimum 3 keystrokes to get anywhere, maybe if leap adopts hop's algo or hop implements the eager hinting then we'll have our sweetspot

@Chaitanyabsprip "eager hinting", by design, is only possible for a 2-character pattern (what to show if there's not input yet?), so it's either 2 keystrokes with pause in-between, or 3 keystrokes without pause, there's no other way.

**Comment by JoannesJ** [comment]
@yanshay 

That does seem like a bug. It probably has something to do with the offset on [`window_context.top_line`](https://github.com/phaazon/hop.nvim/blob/9b2df92594f04d729f3e0f2eb7a5cd691c5c23fa/lua/hop/window.lua#L10). But I don't remember why that was there.

> I wonder what would be the proper way to expose this functionality for consistent results.

I don't use Hop anymore, so don't have a strong opinion. Exposing `x_bias`, or hard-coding a current line bias; they both seem fine.

**Comment by phaazon** [comment]
I think adding another way of labelling could be done by removing the « sort by distance to cursor » and instead « sort by distance to the top-left corner of the buffer view ». That should be fairly simple to do, it’s just not there.

**Comment by yanshay** [comment]
@phaazon
The issue is about consistent hints. The way I see it mostly about - if I know I need the first or second or third occurance of a target, I know which hint letter to press before I even start typing. So for example, if I want to reach the second 'i', I know to press 'is' (assuming keys are as 'asdghk...') . I believe this requirement is usually relevant mostly for the current line, maybe for nearby lines as well.

If distance would be from top-left corner of buffer, then it would also be inconsistent from that respect, isn't that the case? On every line the second 'i' after the cursor would have a different hint.

So the solution IMO is first a fix to the bug above, not sure if the fix I suggested (simply adding 1 to the subtraction) is correct because I don't know what drives the incorrect calculation, maybe it depends on other configurations that cause the offset.

And then on top of that, the distance for nearby lines should take precedence over the standard distance. But to get consistency it needs to be distance from cursor. I implemented such modification for current line above as well.

Or maybe, even better, distance could be to prioritize the first closest occurrences that are in continuation to the text (to the extent a person can see in advance, let's say up to 5) and after that go back to standard distant calculation (which I guess, there's a reason to having it using the current algorithm). Such solution seems more complex to achieve than the first option.

**Comment by ggandor** [comment]
Frankly, I don't understand the point of this whole long discussion here. If the search is bidirectional, then the hints _cannot_ be made predictable - you either want to go forward or backward, but there can be matches in both directions, and Hop cannot read your thoughts. And if the search is directional (AC/BC), then where's the problem (just keep their original order, as they follow each other in the buffer)?

**Comment by yanshay** [comment]
> And if the search is directional (AC/BC), then where's the problem (just keep their original order, as they follow each other in the buffer)?

This is the relevant case, and they don't follow each other in current implementation. It's based on a distance calculation and a match in the row below could be closer than a match in current row. So it's unpredictable and you can't use Hop for macros because of that, which I see as a major limitation. To create a macro I need to disable hop, record/replay a macro with f/F, use it and then re-enable the macro.

**Comment by ggandor** [comment]
And the solution is trivial then, just add a conditional check which skips the unnecessary sorting step for AC/BC motions.
