### ISSUE TITLE
ctrl + o does't jump back to previous cursor location 

### ISSUE THREAD

**Issue by cambp4** [phaazon/hop.nvim#2]
I think everything is in the title, after using :VroomWord <C>-o does't jump back to the previous cursor location. I think it's more of a missing feature than a bug but I thought it was worth mentioning.

**Comment by phaazon** [comment]
Indeed, nice one. I’ll add support for that, thanks.

**Comment by phaazon** [comment]
Should be fixed in 09b9700.
