### ISSUE TITLE
VSCode compatibility

### ISSUE THREAD

**Issue by HaleTom** [phaazon/hop.nvim#206]
I'm trying to select a jump-movement plugin.

How well does this one work with VSCode?

**Comment by yashlala** [comment]
I'm a bit confused -- this plugin is for [neovim](https://neovim.io/) only, not VSCode. 

Are you [embedding neovim in VSCode](https://github.com/asvetliakov/vscode-neovim) somehow?

**Comment by HaleTom** [comment]
Yes, I am using that VSCode plugin.

**Comment by phaazon** [comment]
I have no idea, never tried that plugin. If you use a plugin that goes through neovim inside VS Code I « guess » it should work, but it depends on how that plugin supports the Neovim API I guess.

**Comment by ibehnam** [comment]
This is my question too. Many devs use VSCode Neovim extension. So far, Leap and Lightspeed work well on VSCode, but Hop hasn't been working so far :/
