### ISSUE TITLE
Two target with same key

### ISSUE THREAD

**Issue by Chaitanyabsprip** [phaazon/hop.nvim#207]
![Screenshot 2021-12-26 at 18 20 31](https://user-images.githubusercontent.com/55058351/147409683-d688f8b6-b1e5-46cf-9904-6ecac27e0107.png)

as you can see in the screenshot, two targets are marked with the same key (k).

**Comment by phaazon** [comment]
Probably a bug with your font? Can you switch to a font that doesn’t look that ambiguous, please?

**Comment by Chaitanyabsprip** [comment]
I'll share my findings.

**Comment by Chaitanyabsprip** [comment]
![Screenshot 2021-12-26 at 22 41 32](https://user-images.githubusercontent.com/55058351/147415380-b9ec4a6b-05a6-44d3-b050-5aa08621dad2.png)

This is with RobotoMono font, still the same results

**Comment by Chaitanyabsprip** [comment]
seems like the terminal characters are not being used. the repetition would ideally happen after a terminal character right?

**Comment by Chaitanyabsprip** [comment]
okay so I found the problem, I had put `h` key in the keys string twice by mistake and that was somehow causing the algo to break. Ideally there should a test to ensure this edge case is gracefully handled

**Comment by phaazon** [comment]
I thought about the keys, so happy it’s that. And yes, I’m going to check that with a warning. Thanks for noticing!

**Comment by phaazon** [comment]
I implemented a check for that using `:checkhealth`.
