### ISSUE TITLE
change color of hints

### ISSUE THREAD

**Issue by cambp4** [phaazon/hop.nvim#21]
I couldn't find this information is in the documentation but I just wanted to mention that as a colour blind person, I really struggle to see the hints, is it possible to customize their colours ?
the default easymotion colour works well for instance

![image](https://user-images.githubusercontent.com/62029155/108639256-81aff280-748b-11eb-8a84-9179cced11d0.png)

**Comment by cambp4** [comment]
Ok I figured it out, just need to do this in our vimrc

hi HopNextKey guifg=#f7wf38
hi HopNextKey1 guifg=#f7wf38
hi HopNextKey2 guifg=#f7wf38

**Comment by ranelpadon** [comment]
Just a heads-up, the `#f7wf38` example above will not work, since it's not a valid HEX color code (due to `w` char, since I used it also for quick testing on my end. Valid HEX code will work though. Thanks

**Comment by vanRooijen** [comment]
> Sorry,I want to know how to change the color in init.lua.

Just put each of the commands in vim.cmd('command')

vim.cmd('hi HopNextKey guifg=#c2c52d')
vim.cmd('hi HopNextKey1 guifg=#c2c52d')
vim.cmd('hi HopNextKey2 guifg=#c2c52d')
