### ISSUE TITLE
How can I use ESC to abort HopChar2?

### ISSUE THREAD

**Issue by jdhao** [phaazon/hop.nvim#212]
My nvim version: 0.6.1

my config for hop.nvim:

```
require('hop').setup({
  case_insensitive = true,
  char2_fallback_key = '<CR>',
})

vim.api.nvim_set_keymap('n', 'f', "<cmd>lua require'hop'.hint_char2()<cr>", {noremap = true})
```

When I start two-char hop mode, sometimes I mistyped the first character and want to abort this search, but it seems that I can not abort the search using `Esc` key. Hop still tries to search the combination: `{first-char}<Esc>` and gives a warning:

> there is no such thing we can see...

I do not think the user will have `Esc` in their text files. Is there an option to abort the search if the user pressed `ESC`?

Note that I have noticed `quit_key = '<Esc>'`, but it does not work in this case.

**Comment by jceb** [comment]
Same here, I'm also interested in a solution for this issue. Pressing `<Esc>` twice does the job but that's on key press too much.

**Comment by phaazon** [comment]
Normally the option you use should be the way to go. Maybe it’s not interpreted correctly, let me have a look.

**Comment by jdhao** [comment]
Okay, I have tried with latest version of hop.nvim, `Esc` indeed works.
