### ISSUE TITLE
[Bug] Calling any hop commands causes error in latest nightly on windows

### ISSUE THREAD

**Issue by dominicmason555** [phaazon/hop.nvim#217]
I have been using Hop in neovim nightly on two windows installs for a while now, but as of a week or two ago, running any hop command, e.g. :HopChar1<CR> and pressing a character, causes the following error to appear:
```lua
E5108: Error executing lua ...im-data\site\pack\packer\start\hop.nvim/lua/hop/hint.lua:97: Expected Lua number
stack traceback:
        [C]: in function 'nvim_buf_set_extmark'
        ...im-data\site\pack\packer\start\hop.nvim/lua/hop/hint.lua:97: in function 'set_hint_extmarks'
        ...im-data\site\pack\packer\start\hop.nvim/lua/hop/init.lua:188: in function 'hint_with_callback'
        ...im-data\site\pack\packer\start\hop.nvim/lua/hop/init.lua:129: in function 'hint_with'
        ...im-data\site\pack\packer\start\hop.nvim/lua/hop/init.lua:327: in function 'hint_char1'
        [string ":lua"]:1: in main chunk
```
After pressing enter to continue, the visible editor text stays dimmed as if the relevant characters to hop to are being highlighted, and this can't be un-dimmed as far as I can tell. No results for the search are shown.

I have tried updating and re-installing both neovim nightly 0.7.0-dev-890-g574a58220 (using scoop) and hop (using packer.nvim, with hop setup being called in my init.lua) but the issue still persists on both my PC and laptop.

**Comment by sean-anticks** [comment]
Having the same issue.

**Comment by dominicmason555** [comment]
It's installed with packer, running git log in the install dir says:
```
commit e3c9fc3ab1e1db6bfb4f19377c53d0e457e0e2e9 (HEAD -> v1, tag: v1.2.0, origin/v1.2, origin/v1)
Merge: d2a9f2a c51d1df
Author: Dimitri Sabadie <dimitri.sabadie@gmail.com>
Date:   Sun Nov 21 12:11:44 2021 +0100

    Merge pull request #190 from phaazon/extension-api-enhancements

    Extension api enhancements
```
Since posting this issue, I have experienced very similar issues with other plugins, on both of my computers with similar configs, which is now making me suspect it might be a common cause issue outside of Hop caused by an update to neovim nightly on windows breaking some compatibility, although I have no idea what specifically.

**Comment by Anticks** [comment]
> It's installed with packer, running git log in the install dir says:
> 
> ```
> commit e3c9fc3ab1e1db6bfb4f19377c53d0e457e0e2e9 (HEAD -> v1, tag: v1.2.0, origin/v1.2, origin/v1)
> Merge: d2a9f2a c51d1df
> Author: Dimitri Sabadie <dimitri.sabadie@gmail.com>
> Date:   Sun Nov 21 12:11:44 2021 +0100
> 
>     Merge pull request #190 from phaazon/extension-api-enhancements
> 
>     Extension api enhancements
> ```
> 
> Since posting this issue, I have experienced very similar issues with other plugins, on both of my computers with similar configs, which is now making me suspect it might be a common cause issue outside of Hop caused by an update to neovim nightly on windows breaking some compatibility, although I have no idea what specifically.

I am on a mac, and facing the same issue. Tested it on my other computer as well. Downgrading Neovim, for now, seems to fix the issue.

**Comment by dominicmason555** [comment]
> I am on a mac, and facing the same issue. Tested it on my other computer as well. Downgrading Neovim, for now, seems to a workaround.

Just tried the same, downgrading from the nightly build to 0.6.1 and that fixed the issue on Windows as well. Hopefully by the time the nightly changes end up in the stable release, the source of this issue will be more well known, as it's affected several other plugins as well.

**Comment by shadmansaleh** [comment]
@phaazon looks like `hint.jump_target.buffer` is `nil` sometimes . On nightly neovim no longer treats nil as 0 on api function calls. Instead throws an error . See relevent breacking change [notice](https://github.com/neovim/neovim/issues/14090#issuecomment-1004318147) . That's why hop is throwing errors .

This patch seems to fix the issue
```diff
diff --git a/lua/hop/hint.lua b/lua/hop/hint.lua
index 0939d83..369fed1 100644
--- a/lua/hop/hint.lua
+++ b/lua/hop/hint.lua
@@ -94,7 +94,7 @@ function M.set_hint_extmarks(hl_ns, hints, opts)
     end
 
     if vim.fn.strdisplaywidth(label) == 1 then
-      vim.api.nvim_buf_set_extmark(hint.jump_target.buffer, hl_ns, hint.jump_target.line, hint.jump_target.column - 1, {
+      vim.api.nvim_buf_set_extmark(hint.jump_target.buffer or 0, hl_ns, hint.jump_target.line, hint.jump_target.column - 1, {
         virt_text = { { label, "HopNextKey" } },
         virt_text_pos = 'overlay',
         hl_mode = 'combine',
@@ -103,7 +103,7 @@ function M.set_hint_extmarks(hl_ns, hints, opts)
     else
       -- get the byte index of the second hint so that we can slice it correctly
       local snd_idx = vim.fn.byteidx(label, 1)
-      vim.api.nvim_buf_set_extmark(hint.jump_target.buffer, hl_ns, hint.jump_target.line, hint.jump_target.column - 1, { -- HERE
+      vim.api.nvim_buf_set_extmark(hint.jump_target.buffer or 0, hl_ns, hint.jump_target.line, hint.jump_target.column - 1, { -- HERE
         virt_text = { { label:sub(1, snd_idx), "HopNextKey1" }, { label:sub(snd_idx + 1), "HopNextKey2" } },
         virt_text_pos = 'overlay',
         hl_mode = 'combine',
```

**Comment by clason** [comment]
> This patch seems to fix the issue 

But that's already been merged: https://github.com/phaazon/hop.nvim/pull/211/files

Are you by any chance pinning a tag (like 1.2.0)? @phaazon you might want to make a bugfix 1.2.1 release with that change.

**Comment by shadmansaleh** [comment]
> Are you by any chance pinning a tag (like 1.2.0)?

Indeed looks like I'm sitting on v1. Thanks clason.
