### ISSUE TITLE
Consider using extmark overlay

### ISSUE THREAD

**Issue by akinsho** [phaazon/hop.nvim#22]
Recently with https://github.com/neovim/neovim/pull/13952 merged you can now actually "overlay" text on top of the contents of the buffer using `extmarks`. One of the stated use cases for this is this exact type of plugin.

>The primary use cases of this display modes would be indent guides as well as EasyMotion style hints. Abusing the indent area for "sign" like display is also possible.

example:
```lua
vim.api.nvim_buf_set_extmark(0, ns, 2, 3, { virt_text={{'--', 'ErrorMsg'}, {'gg', 'String'}}, virt_text_style='overlay'})
```

I think this might potentially simplify your implementation since you won't have to maintain a window on top of the current buffer, although that's just a guesstimation.

**Comment by phaazon** [comment]
Yeah, I really want to use this! Thanks for the recommendation!

**Comment by akinsho** [comment]
Gonna close this now since you've implemented using extmarks 🎉
