### ISSUE TITLE
Can't use hop command in neovim

### ISSUE THREAD

**Issue by coderj001** [phaazon/hop.nvim#220]
![image](https://user-images.githubusercontent.com/39460245/151116950-2adc7201-8579-4b33-9842-65125f6a3f48.png)

**Comment by SheepYY039** [comment]
same issue here

**Comment by SheepYY039** [comment]
when using `:HopChar1` and typing any letter, no hint shows up and sometimes all syntax highlighting on the file disappeared. 
![image](https://user-images.githubusercontent.com/56354081/151642684-f1c41c09-6efd-4da0-b8f9-a93f27680970.png)

**Comment by curist** [comment]
Got the same issue using `v1` branch with neovim v0.7.0; but latest version of `hop.nvim` works.
Relevant fix is in commit https://github.com/phaazon/hop.nvim/commit/b33e02f8c6d0f3086359bf3b9acf62c218b24344, which isn't in released yet.

**Comment by coderj001** [comment]
Well i have switch to easymotion, as i cannot config hop.

**Comment by coderj001** [comment]
> I’m going to have a look at this problem tonight or tomorrow, thanks for noticing.

**Comment by dominicmason555** [comment]
I think this is the same issue I was having in #217, so far I had downgraded to Neovim v0.6.1 which fixed the issue, although now I think the problem was I had copied the following line in the installation with packer instructions from the README:
```lua
  branch = 'v1', -- optional but strongly recommended
```
since this branch does not contain the fix @curist mentioned, removing this line may fix the issue

**Comment by phaazon** [comment]
Yeah, I haven’t made a `v1` release for a while. The thing is, if you are using the stable neovim, you shouldn’t have issues. If you do, then something is wrong with the code that assumes `set_hint_extmarks` expects a number. I’m fixing this today.

**Comment by phaazon** [comment]
My neovim Treesitter parser for Lua is completely broken; I’ll try fixing that first though.

**Comment by dominicmason555** [comment]
By removing the line about pinning the v1 branch I've got it working again in the latest nightly, but yeah v1 did still work with the stable neovim release 0.6.1

**Comment by phaazon** [comment]
This is now fixed. Sorry for the long delay, my life and OSS didn’t really cross paths lately.
