### ISSUE TITLE
Pressing <Esc> after :HopChar1 triggers error "-> there's no such thing we can see"

### ISSUE THREAD

**Issue by cmvanb** [phaazon/hop.nvim#225]
After invoking `:HopChar1`, pressing `<Esc>` (or the quit_key, if assigned to something else) triggers an error `"-> there's no such thing to see"`.

As a user I would expect no error, since I'm not searching for `<Esc>`, I'm quitting Hop.

I didn't notice this behavior with `:HopWord`.

packer setup:
```
    use 'phaazon/hop.nvim'

    require('hop').setup({
        quit_key = '<esc>',
    })
```

**Comment by phaazon** [comment]
I don’t reproduce.

**Comment by cmvanb** [comment]
Bug was still present on my system. After PackerSync it is resolved- you must have fixed it in the last 8 weeks! :)
