### ISSUE TITLE
`HopChar1BC` skips characters from current line

### ISSUE THREAD

**Issue by FelipeLema** [phaazon/hop.nvim#237]
Example, take the following lua code from `cmp-buffer`

```lua 
  self.opts = opts
  self.regex = vim.regex(self.opts.keyword_pattern)
```

If I'm standing at `k` in `keyword_pattern` and use `<cmd>HopChar1BC<CR>`, then press `s` it will offer me to jump to any of `s` in `self.opts = opts`, but none in the same line.

I expect the command to _also_ offer me to jump to characters in the same line, before the cursor

**Comment by FelipeLema** [comment]
worth noting: `HopChar1AC` does include characters from current line as I expect it to

**Comment by mraxilus** [comment]
This is an issue for me as well; AC includes current line, but BC doesn't.

**Comment by yashlala** [comment]
I'm running into this issue as well. It seems like it's not restricted to the current line either; it also affects positions in the previous line if their column number is greater than the current cursor column. 

To make it more clear: C is the cursor, O represents jumpable (correct) characters, X represents the skipped (buggy) locations:  

```
XXXXXXXXXXXXXOOOOOOOOOOOO
OOOOOOOOOOOOCOOOOOOOOOOOO
OOOOOOOOOOOOOOOOOOOOOOOOO
```
