### ISSUE TITLE
`HopWordBC` no longer targets the current line, but `HopWordAC` still does.

### ISSUE THREAD

**Issue by iago-lito** [phaazon/hop.nvim#246]
Hello, I've got this new behaviour after a fresh reinstall of my system. I'm not sure it's expected, or whether there is a way to work around it. Any idea?

The situation 
after `:HopWordAC` (current line included)
![AC](https://user-images.githubusercontent.com/10091387/171374489-d9a590dc-e749-4339-ba6b-8a9f7340327c.png)

The situation after `:HopWordBC` (current line excluded)
![BC](https://user-images.githubusercontent.com/10091387/171374568-f3ae78c3-68e5-4b62-853b-46fb3bd294ce.png)

How can I include the current line when asking to `HopWordBC`?

```sh
$ uname -a
Linux etak 5.18.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 30 May 2022 17:53:11 +0000 x86_64 GNU/Linux

$ nvim --version
NVIM v0.8.0-dev+340-gb7d70de345
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

$ cd hop.nvim && git rev-parse HEAD
b93ed4cea9c7df625d04e41cb15370b5c43cb578
```

**Comment by tssm** [comment]
I can confirm this issue :(

**Comment by tssm** [comment]
Same issue with `HopChar1BC`

**Comment by tssm** [comment]
I updated all my plug-ins today and seems one of the latest two merges fixed it
