### ISSUE TITLE
when we execute any Hop function and set cmdheight=0,there occurs blue line on the left of statusline.

### ISSUE THREAD

**Issue by Baitur5** [phaazon/hop.nvim#252]
<img width="180" alt="image" src="https://user-images.githubusercontent.com/73650784/174486436-ac905682-7f1e-4022-aeb5-7d9188fc2d2e.png">

**Comment by ggandor** [comment]
That is the cursor, the same you see without `cmdheight=0`, since technically a `vim.fn.getchar` call happens when the plugin gets user input. There is no clean way to make that real cursor disappear.
