### ISSUE TITLE
Use incluse_jump in operator mode

### ISSUE THREAD

**Issue by tobealive** [phaazon/hop.nvim#256]
Alternatively, this probably could be solved adjusting hint_offset for operator mode. Currently, as far as I can test it's not possible to adjust the new hint_offset to get this working.

An example reproduction would be to use hop for a deletion of a line with a motion command
```lua
vim.keymap.set('o', 'f', "<cmd>lua require'hop'.hint_char1({ direction = require'hop.hint'.HintDirection.AFTER_CURSOR, current_line_only = true, inclusive_jump = true})<cr>")
```
having a line of text like
`delete This`
<kbd>dfT</kbd> won't delete the `T`

---

edit: of course it should be **inclusive**_jump in the title.

Also, there was another issue already opened that mentions the deprecated state of inclusive jump #253.
I just installed the GitHub browser extension and some auto filtering for profiles and issues is going on, so I couldn't find checking the issue section the classical way. I should have checked better.

**Comment by ChristianChiarulli** [comment]
https://github.com/phaazon/hop.nvim/issues/257

Fixing this issue and and setting `hint_offset = 1` should solve this

**Comment by phaazon** [comment]
Yes indeed, `inclusive_jump` is now dead.
