### ISSUE TITLE
Off by 1 issue with new API

### ISSUE THREAD

**Issue by ChristianChiarulli** [phaazon/hop.nvim#257]
If you set the following for instance:

```
vim.api.nvim_set_keymap('', 'f', "<cmd>lua require'hop'.hint_char1({ direction = require'hop.hint'.HintDirection.AFTER_CURSOR, current_line_only = true, hint_offset = 1 })<cr>", {})
```

This will offset by 2 characters instead of 1 due to

https://github.com/phaazon/hop.nvim/blob/a3cf6684bcb9fc974609ae81424f285f05280d90/lua/hop/init.lua#L265 and https://github.com/phaazon/hop.nvim/blob/a3cf6684bcb9fc974609ae81424f285f05280d90/lua/hop/init.lua#L270

**Comment by phaazon** [comment]
Do you still reproduce? I don’t anymore (I didn’t try when you opened the issue, sorry for asking you to update and check again).

**Comment by JoseConseco** [comment]
I tried with and without using 'feature/cursor-offset' branch.  
+1 offset if jumping 2 letter rather than 1.  (using for f - makes operator consume 2 letters - selected and next one)
- 0 offset for 'f' motion - wont consume target letter.
Below - dfn   - wont delete  [n]vim letter. 
https://user-images.githubusercontent.com/13521338/176996681-844d6be4-c3bc-4206-9d4e-aada7756af8a.mp4

**Comment by ChristianChiarulli** [comment]
Yea I still have the issue, this PR fixes it: https://github.com/phaazon/hop.nvim/pull/265/files

```
if hint_offset ~= nil and not (hint_offset == 0) then -- hint offset = 1
    column = column + hint_offset -- column + 1
    local buf_line = vim.api.nvim_buf_get_lines(vim.api.nvim_win_get_buf(w), line - 1, line, false)[1]

    -- If it is pending for operator shift column to the right by 1
    if vim.api.nvim_get_mode().mode == 'no' then -- we are in pending operator mode by pressing df<char>
      column = column + 1 -- column + 1 (this is the second time column is incremented, which will now over shoot by 1)
    end

    column = vim.fn.byteidx(buf_line, column)
  end
```

**Comment by iroedius** [comment]
@ChristianChiarulli Thanks, I tried your binding for T and unfortunately it's not right, it cuts 1 letter less than it should. These are my keymaps for reference, with #265 applied all work except the last one ('T' with 'o', doesn't work right regardless of the value of hint_offset, and hint_offset here behaves identically with values '-1' and '0', which must be a bug):
```
vim.keymap.set({'n', 'x', 'o'}, 'f', function() require('hop').hint_char1({ direction = require('hop.hint').HintDirection.AFTER_CURSOR, current_line_only = true }) end, default_opts)
vim.keymap.set({'n', 'x', 'o'}, 'F', function() require('hop').hint_char1({ direction = require('hop.hint').HintDirection.BEFORE_CURSOR, current_line_only = true }) end, default_opts)
vim.keymap.set({'n', 'x'}, 't', function() require('hop').hint_char1({ direction = require('hop.hint').HintDirection.AFTER_CURSOR, current_line_only = true, hint_offset = -1 }) end, default_opts)
vim.keymap.set({'o'}, 't', function() require('hop').hint_char1({ direction = require('hop.hint').HintDirection.AFTER_CURSOR, current_line_only = true, hint_offset = -2 }) end, default_opts)
vim.keymap.set({'n', 'x'}, 'T', function() require('hop').hint_char1({ direction = require('hop.hint').HintDirection.BEFORE_CURSOR, current_line_only = true, hint_offset = 1 }) end, default_opts)
vim.keymap.set({'o'}, 'T', function() require('hop').hint_char1({ direction = require('hop.hint').HintDirection.BEFORE_CURSOR, current_line_only = true, hint_offset = -1 }) end, { silent = true })
```

**Comment by ChristianChiarulli** [comment]
Awesome thanks for confirming @iroedius. @phaazon

**Comment by JoseConseco** [comment]
@phaazon any chance fixing this?  the way hop is now, it is impossible to setup f F , correctly (hop motion is not reaching target character).  They work same way as t T (which works ok - operator stops before target letter)

**Comment by stCarolas** [comment]
sorry for commit spam((

but for me this PR fixes this issue
https://github.com/phaazon/hop.nvim/pull/293

**Comment by stCarolas** [comment]
@ChristianChiarulli with your PR I have a problem with deleting by 'hint_words' - it will delete first letter of word by default. It differs from `dw` which delete _until_ first letter

**Comment by phaazon** [comment]
I will have a look at this today , thanks.
