### ISSUE TITLE
Setting custom keys repeats unusable matches

### ISSUE THREAD

**Issue by tversteeg** [phaazon/hop.nvim#263]
### Config

```lua
use {
    "phaazon/hop.nvim",
    config = function()
        require("hop").setup({ keys = "uhetonaspg.c,rkmjwv" })
    end,
}
```

### `:HopWord`

![image](https://user-images.githubusercontent.com/2574730/175312555-0efe52bd-3902-4930-96b2-8791bd5e9da8.png)

Now when I press `h` for example it just jumps to the first match on the screen, not giving me the opportunity to jump down.

**Comment by stefanwatt** [comment]
I was about to post about this exact same issue.
Kinda weird that the "one of the most important, if not the most" configuration option is broken.

**Comment by phaazon** [comment]
I just saw that issue. That’s weird, indeed, I don’t reproduce and I use it (bépo layout). I will have a look.

**Comment by m0lentum** [comment]
Just ran into this and found that removing the dot character from the keys list fixed it for me. Maybe dots are getting interpreted as a pattern instead of a literal somewhere?
