### ISSUE TITLE
Bidirectional `t` like motion?

### ISSUE THREAD

**Issue by shyun3** [phaazon/hop.nvim#266]
Hello, it looks like Hop now supports proper `t` like motion thanks to #191. I was trying to create a bidirectional `t` hop mapping, but I'm seeing an issue. Here's what I've been testing with:
```
vim.api.nvim_set_keymap('', 't', "<cmd>lua require'hop'.hint_char1({ hint_offset = -1 })<cr>", {})
```
This works as expected if I'm hopping to a character after the cursor. However, if I'm hopping before the cursor, the new cursor will appear before the target character (closer to column 1) instead of after (closer to the end of the line).

I guess what I'm looking for is a hop that will conditionally set `hint_offset` to -1 if jumping after the cursor and to 1 before the cursor. Is this currently possible?

**Comment by shyun3** [comment]
Just looking for `t` and `T` in one command. Something like `:HopChar1` except using a `t` motion. It would be nice if this could be implemented by a function, but I'm not sure I see a way. Any help would be appreciated.

**Comment by mcauley-penney** [comment]
I misunderstood and see what you're saying now, thank you for explaining. 

I think the relevant part of the documentation that explains how to implement something like this is the Jump Target API (`:h hop-jump-target-api` or ctrl-f "Jump Target API" [here](https://github.com/phaazon/hop.nvim/blob/master/doc/hop.txt)). This allows you to create your own functionality using Hop.

**Comment by shyun3** [comment]
I think I've come up with something. It's quite messy and I had to steal a lot of code from hop. In case anyone is interested:
```lua
-- Derived from `hop.hint_with()`
local function hintWithTill(jump_target_gtr, opts)
  if opts == nil then
    -- Taken from override_opts()
    opts = setmetatable(opts or {}, {__index = require'hop'.opts})
  end

  require'hop'.hint_with_callback(jump_target_gtr, opts, function(jt)
    local jumpLine = jt.line + 1
    local jumpCol = jt.column - 1

    local curPos = vim.api.nvim_win_get_cursor(0)
    local row = curPos[1]
    local col = curPos[2]

    local hintOffset
    if row > jumpLine or (row == jumpLine and col > jumpCol) then
      hintOffset = 1
    else
      hintOffset = -1
    end

    require'hop'.move_cursor_to(jt.window, jumpLine, jumpCol, hintOffset)
  end)
end

-- Derived from `hop.get_input_pattern()`
local function getInputChar(prompt)
  local K_Esc = vim.api.nvim_replace_termcodes('<Esc>', true, false, true)
  local K_BS = vim.api.nvim_replace_termcodes('<BS>', true, false, true)
  local K_CR = vim.api.nvim_replace_termcodes('<CR>', true, false, true)
  local key = ''

  vim.api.nvim_echo({}, false, {})
  vim.cmd('redraw')
  vim.api.nvim_echo({{prompt, 'Question'}, {key}}, false, {})

  local ok, key = pcall(vim.fn.getchar)
  if not ok then return key end -- Interrupted by <C-c>

  if type(key) == 'number' then
    key = vim.fn.nr2char(key)
  elseif key:byte() == 128 then
    -- It's a special key in string
  end

  if key == K_Esc or key == K_CR or key == K_BS then
    key = nil
  end

  vim.api.nvim_echo({}, false, {})
  vim.cmd('redraw')
  return key
end

-- Derived from `hop.hint_char1()`
function hintTill1(opts)
  -- Taken from override_opts()
  opts = setmetatable(opts or {}, {__index = require'hop'.opts})

  local c = getInputChar('Till 1 char: ')
  if not c then
    return
  end

  local generator = require'hop.jump_target'.jump_targets_by_scanning_lines
  hintWithTill(
    generator(require'hop.jump_target'.regex_by_case_searching(c, true, opts)),
    opts
  )
end
```

An example of the function being used in some mappings:
```vim
noremap <KEY> <Cmd>lua hintTill1()<CR>
onoremap <KEY> V:lua hintTill1()<CR>
```

**Comment by kiyoon** [comment]
It would be nice to see this implemented officially.

I don't care if I'm going forward or backward, I just want to use `f` and `t` without separating them from `F`and `T`.
In order for this to work, I need the hint offset to be 1 when going backwards, and -1 when going forwards with `t`.
