### ISSUE TITLE
Yet another inclusive_jump question...

### ISSUE THREAD

**Issue by lyndhurst** [phaazon/hop.nvim#269]
Hi,

I am sorry if I am spamming the issue tracker, but I am a bit confused. I am trying to replace vanilla vim `t` & `f` with hop motions as well as many other users as far as I can tell, and I did a lot of trial and errors trying to make it work before reading #256.

As the OP referenced there, #253 states that `inclusive_jump` is about to be deprecated in favor of `hint_offset`, and #257 suggests that, even if it needs fixing, `hint_offset` is already working.

This is where I get confused. After playing around with the config, I can say that in my case `hint_offset` has no effect whatsoever in any mode. On the other hand using `inclusive_jump` I got everything working fine in both normal and operator pending mode except for `t` in normal mode.

My questions are: 
1. Should I be prepared to have to change my config again to use `hint_offset` instead of `inclusive_jump` in the near future?
2. Is it normal that `hint_offset` does not have any effect on my side? Maybe it is being developed in another branch...
3. Which issue should I follow to keep up with this matter, and know when to adjust my config?

Thank you for your time, and sorry again if I am bloating the issues without adding any value.

PS: This is how I got everything working except for `f` in normal mode if it is of any interest to someone...

```lua
local keymap = vim.api.nvim_set_keymap

-- Replace f & F with hop motions.
keymap('n', 'f', "<cmd>lua require'hop'.hint_char1({ direction = require'hop.hint'.HintDirection.AFTER_CURSOR, current_line_only = true })<cr>", {})
keymap('o', 'f', "<cmd>lua require'hop'.hint_char1({ direction = require'hop.hint'.HintDirection.AFTER_CURSOR, current_line_only = true, inclusive_jump = true})<cr>", {})
keymap('n', 'F', "<cmd>lua require'hop'.hint_char1({ direction = require'hop.hint'.HintDirection.BEFORE_CURSOR, current_line_only = true })<cr>", {})
keymap('o', 'F', "<cmd>lua require'hop'.hint_char1({ direction = require'hop.hint'.HintDirection.BEFORE_CURSOR, current_line_only = true })<cr>", {})

-- Replace t & T with hop motions.
keymap('o', 't', "<cmd>lua require'hop'.hint_char1({ direction = require'hop.hint'.HintDirection.AFTER_CURSOR, current_line_only = true })<cr>", {})
keymap('n', 'T', "<cmd>lua require'hop'.hint_char1({ direction = require'hop.hint'.HintDirection.BEFORE_CURSOR, current_line_only = true, inclusive_jump = true })<cr>", {})
keymap('o', 'T', "<cmd>lua require'hop'.hint_char1({ direction = require'hop.hint'.HintDirection.BEFORE_CURSOR, current_line_only = true, inclusive_jump = true })<cr>", {})

```

**Comment by phaazon** [comment]
> Should I be prepared to have to change my config again to use hint_offset instead of inclusive_jump in the near future?

Yes, it’s now the default.

> Is it normal that `hint_offset` does not have any effect on my side? Maybe it is being developed in another branch...

It depends. How do you install Hop? Do you use a branch (`v1`?). If so, then yes, it’s normal, it’s currently a nightly feature. I’m about to make a new release in the incoming days. You can temporarily switch to the nightly version by using `branch = 'master'` with `packer` (or nothing, it’s the default).

> Which issue should I follow to keep up with this matter, and know when to adjust my config?

Eh, good question. I don’t do pre-releases, most of the time, users use and talk about nightly features as if they were already available. I should probably develop all that in a non-master branch to prevent that, but yeah, maybe I should probably start creating issue for new incoming releases. I’m probably going to do that, it’s a pretty good idea.
