### ISSUE TITLE
virtualedit mode regression

### ISSUE THREAD

**Issue by phaazon** [phaazon/hop.nvim#27]
See [this](https://github.com/phaazon/hop.nvim/pull/14/files#diff-5dc228ff2a63872d5d004af9e04cf49da68ee817118c9103347437f04e1675acR48-R49).

**Comment by phaazon** [comment]
I don’t seem to reproduce anymore, so I’m going to close this. Maybe it was just a weird issue on my side.

**Comment by phaazon** [comment]
Nevermind it just happened again, I need to investigate that.

**Comment by Dreomite** [comment]
To reproduce, try searching for a non-existant character.
This is https://github.com/phaazon/hop.nvim/commit/b844a533d654271c66cea44182522a56b2d0c8c1 regression. If there are 0 hints, `hint_with()` returns before restoring `virtualedit` option.

**Comment by phaazon** [comment]
Nice catch. I’ll fix that tomorrow. :)

**Comment by phaazon** [comment]
This should be done by now thanks to extended marks. Closing again. :)
