### ISSUE TITLE
init.lua:127: end_col value outside range when exec :HopChar1BC at empty line

### ISSUE THREAD

**Issue by tomasky** [phaazon/hop.nvim#277]
init.lua:127: end_col value outside range when exec :HopChar1BC at empty line or blank

**Comment by semanser** [comment]
I had the same issue with this command:

```
vim.api.nvim_set_keymap('', 'S', "<cmd>lua require'hop'.hint_words({ direction = require'hop.hint'.HintDirection.AFTER_CURSOR })<cr>", {})
```

Removing all the params solved the problem:
```
vim.api.nvim_set_keymap('', 'S', "<cmd>lua require'hop'.hint_words()<cr>", {})
```

**Comment by mystilleef** [comment]
Same problem with `HopLineAC` and `HopLineBC`.

**Comment by brettmitchelldev** [comment]
Same issue here with a manual binding as @semanser is seeing.

Broken binding: `vim.api.nvim_set_keymap('', '<leader>j', ":lua require'hop'.hint_lines { direction = require'hop.hint'.HintDirection.AFTER_CURSOR } <enter>")`  
Working binding: `vim.api.nvim_set_keymap('', '<leader>j', ":lua require'hop'.hint_lines {} <enter>")`  

This occurs:  
1. On empty lines.  
2. At the end of a line, but only when getting there with the `$` motion. Using `l`, `e`, or `f` does not cause the issue.

**Comment by brettmitchelldev** [comment]
@iago-lito Does it sound like your issue (https://github.com/phaazon/hop.nvim/issues/289) might be related to this? I've just started using Hop, so I don't know the ins and outs of the codebase yet, but from the original issue, it sounds like it might be related.

**Comment by tomasky** [comment]
confirmed that the latest version has fixed this problem, so close it
