### ISSUE TITLE
Update example keybinding setup in the README

### ISSUE THREAD

**Issue by ehllie** [phaazon/hop.nvim#285]
The current snippet with example keybinding setup at the bottom of the README file, defines keybinds using the vim api from inside lua, and the content of those keybinds is a command that invokes lua code to run a lua function from within vim.
```lua
-- place this in one of your configuration file(s)
vim.api.nvim_set_keymap('', 'f', "<cmd>lua require'hop'.hint_char1({ direction = require'hop.hint'.HintDirection.AFTER_CURSOR, current_line_only = true })<cr>", {})
vim.api.nvim_set_keymap('', 'F', "<cmd>lua require'hop'.hint_char1({ direction = require'hop.hint'.HintDirection.BEFORE_CURSOR, current_line_only = true })<cr>", {})
vim.api.nvim_set_keymap('', 't', "<cmd>lua require'hop'.hint_char1({ direction = require'hop.hint'.HintDirection.AFTER_CURSOR, current_line_only = true, hint_offset = -1 })<cr>", {})
vim.api.nvim_set_keymap('', 'T', "<cmd>lua require'hop'.hint_char1({ direction = require'hop.hint'.HintDirection.BEFORE_CURSOR, current_line_only = true, hint_offset = 1 })<cr>", {})
```
That is a little contrived, and makes it hard to understand what the keybind does at a glance. Since the vim api supports passing either strings or lua functions, and the string being passed currently already invokes a lua function, I propose we just passing a lua function directly.

```lua
-- place this in one of your configuration file(s)
local hop = require("hop")
local directions = require("hop.hint").HintDirection
vim.api.nvim_set_keymap("", "f", function()
  hop.hint_char1({ direction = directions.AFTER_CURSOR, current_line_only = true })
end, {})
vim.api.nvim_set_keymap("", "F", function()
  hop.hint_char1({ direction = directions.BEFORE_CURSOR, current_line_only = true })
end, {})
vim.api.nvim_set_keymap("", "t", function()
  hop.hint_char1({ direction = directions.AFTER_CURSOR, current_line_only = true, hint_offset = -1 })
end, {})
vim.api.nvim_set_keymap("", "T", function()
  hop.hint_char1({ direction = directions.BEFORE_CURSOR, current_line_only = true, hint_offset = 1 })
end, {})
```
`hop` and `hop.hint.HintDirection` could also be put in a local variable to avoid calling `require` 8 times.

**Comment by kittywitch** [comment]
Shouldn't this be using vim.keymap.set with remap=true? When I tried these changes, Neovim was expecting a lua string instead of a function. vim.keymap.set allows the RHS to be a lua function, in comparison to nvim_set_keymap. 

Please correct / ignore me if I'm mistaken.
