### ISSUE TITLE
Reopening #193

### ISSUE THREAD

**Issue by iago-lito** [phaazon/hop.nvim#289]
Hi, I'm sorry I'm running into #193 again on fresh master a7ad781 and I could not find a `reopen` button there, here is the error message now
```
E5108: Error executing lua /home/iago-lito/.vim/plugged/hop.nvim/lua/hop/init.lua:127: col value outside range
```

**Comment by jamestrew** [comment]
I'm running into this issue as well.
Specifically getting the error when using `HopWordBC` & `HopWordAC` on a blank line much like #277

**Comment by phaazon** [comment]
Duplicate of #261.
