### ISSUE TITLE
BufEnter event is triggered when jumping

### ISSUE THREAD

**Issue by voldikss** [phaazon/hop.nvim#29]
I want to enter INSERT mode as soon as entering a terminal buffer so I defined the following auto command for myself.

```vim
autocmd BufEnter term://* startinsert
```

However, this autocmd prevents me from jumping around in the terminal window because when I type some keys, the hop window will be closed and `BufEnter` event will be triggered, which takes me into the TERMINAL mode and ... no jump...

In general, a lot of users would have some `BufEnter` autocmds predefined. Thus, in order to avoid possible side effects,  I think it would be better if we use `noautocmd` when closing hop window. How do you think about this?

![hop](https://user-images.githubusercontent.com/20282795/109582544-4ff8f480-7b39-11eb-8a90-c2ab9d15ff7f.gif)

**Comment by phaazon** [comment]
I think that’s perfectly fair; if we can disable autocommands for that buffer, I’m all in. It would also fix issues with people running whitespace plugins, I guess.

**Comment by voldikss** [comment]
Wow, today I use the plugin again and found that this issue has been solved.
