### ISSUE TITLE
[Question] How to make f/F/t/T behave like clever-f.vim?

### ISSUE THREAD

**Issue by vihu** [phaazon/hop.nvim#291]
I was wondering if it would be possible with the current code to make `f`, `F`, `t` and `T` behave like [clever-f](https://github.com/rhysd/clever-f.vim), specifically the first [gif](https://raw.githubusercontent.com/rhysd/ss/master/clever-f.vim/cleverf_main.gif) over there.

So essentially:
1. Press `f<letter>`
2. Highlight only the `<letter>` in the current line (_without_ any modification, i.e. keep the `<letter>` highlighted as is).
3. Press `f` repeatedly to move between occurrences of `<letter>` (Bonus points for making it dot-repeatable and/or hop directly to `X` occurrence with a `X` number)

If the current code does not support this functionality, I'd be happy to give it a try with some guidance :slightly_smiling_face: 

PS: Thank you very much for your excellent plugin!

**Comment by phaazon** [comment]
Hey!

No, that’s not how Hop works. It’s not about highlighting, even though it has some highlighting capabilities (for dimming and hinting). Hop works by allowing you to jump _directly_ to something. It doesn’t support iterative workflows. For that, other projects exist, such as `vim-sneak`.

Nevertheless, you can try to implement something like that in Hop by going with an Hop extension (`:h hop-extension`), but I will not merge that upstream as it’s a bit against the philosophy of jump targets.

**Comment by vihu** [comment]
> Hey!
> 
> No, that’s not how Hop works. It’s not about highlighting, even though it has some highlighting capabilities (for dimming and hinting). Hop works by allowing you to jump _directly_ to something. It doesn’t support iterative workflows. For that, other projects exist, such as `vim-sneak`.
> 
> Nevertheless, you can try to implement something like that in Hop by going with an Hop extension (`:h hop-extension`), but I will not merge that upstream as it’s a bit against the philosophy of jump targets.

Understood, thank you for the response!
