### ISSUE TITLE
hint_patterns should not throw exception when the pattern is not completed

### ISSUE THREAD

**Issue by glyh** [phaazon/hop.nvim#295]
For example:
When I enter `hel[`, hop should not throw an exception, but should wait until the input is legal.

**Comment by phaazon** [comment]
I don’t understand the issue, nor what is that `hel[`.

**Comment by glyh** [comment]
So when you're entering a regex, it's prefix is not guarantee to be a valid regex. hop seems to detect the prefix not to be valid and throw an exception.
