### ISSUE TITLE
A lot of hints require 3 keystrokes

### ISSUE THREAD

**Issue by cambp4** [phaazon/hop.nvim#3]
Hi, as the title says. a lot of hints require 3 keystrokes whereas easymotion mostly require max 2 keystrokes. is it something that can be configured ?

**Comment by phaazon** [comment]
Yep.

```vim
:help hop-config-keys
```

The default keys for `qwerty` (default) is the same as EasyMotion, but the current algorithm for generating the permutation is based on a percentage of sequence keys vs. terminal keys. You can tweak that with `tem_seq_bias`.

```vim
:help hop-config-term_seq_bias
```

Long term, I want to have a fully balanced solution. I need to investigate a bit more into that direction. :)

**Comment by cambp4** [comment]
how do I write this into my init file? it would be siper helpful to have a config demo in the readme like most plugin do so that it can get us started. 

cause is the doc it says hop-config-keys is the setting, but how should write this ?

**Comment by phaazon** [comment]
I’ll add a little something to explain this. :)

**Comment by phaazon** [comment]
So, I just realized that there _is_ actually a way to enhance the situation. It should be possible to compute the optimal number of terminal keys in a way that we can share some of them as sequence keys too. For instance, if `a b c` are compose keys and `d e f` are terminal keys, these are sequences are possible (assuming a maximum depth of 3):

- `d`, `e` and `f`.
- `ad`, `abe`, etc.
- `aba`, `abb` and `abc`, even though ending with a compose keys, are valid!

The big question is: how do we know when we have enough keys to end up a depth level. The number of hints is always know when generating the permutations, so I think it should be “quite easy” to deduce if we can use a compose key as terminal (and then removing a layer, yielding most of the situations on only two keys).

**Comment by phaazon** [comment]
This is now implemented. I’m going to push that today, I just need to polish a bit the documentation / clean a bit the code, but it should be available today!

## Current algorithm

![img_031421_142452](https://user-images.githubusercontent.com/506592/111070290-6310aa80-84d1-11eb-951d-761ea8070765.png)

## New algorithm

![img_031421_142504](https://user-images.githubusercontent.com/506592/111070301-6e63d600-84d1-11eb-86f5-db476e9a39f9.png)

**Comment by phaazon** [comment]
Fixed in #45 and live on `master`.
