### ISSUE TITLE
Disable when reading or writing macros

### ISSUE THREAD

**Issue by dotwilliamrc** [phaazon/hop.nvim#301]
It would be great if they add an option to disable the plugin when reading or writing macros

**Comment by phaazon** [comment]
Not sure what that means.

**Comment by piersolenski** [comment]
A command such as `:HopToggle` could be useful both for this use case and I imagine many others.

**Comment by snuffop** [comment]
Well it seems now after reading this, having the same issue,  would it not be since f and F are set in the keymaps, that one would toggle that?  Hop is just called via key map yes?
