### ISSUE TITLE
How to create a pattern that combines word and empty line

### ISSUE THREAD

**Issue by jjiangweilan** [phaazon/hop.nvim#308]
I have tried to extend the `regex_by_word_start` with `^\s*$` and `^\s\+$`
```
function M.regex_by_word_start()
  return M.regex_by_searching('\\(\\k\\+\\)\\|\\(^\\s\\*$\\)')
end
```
with the plus sign version `\\(\\k\\+\\)\\|\\(^\\s\\+$\\)` I can make it work with line with spaces, but not empty line.
![image](https://user-images.githubusercontent.com/13493742/186566077-e78892e8-7050-4d7b-bdef-f8ee5e7489e6.png)

**Comment by phaazon** [comment]
I would recommand writing a jump target generator completely from scratch. You can have a look at `regex_by_word_start`, which uses `regex_by_searching`:

```lua
-- Regex by searching a pattern.
function M.regex_by_searching(pat, plain_search)
  if plain_search then
    pat = vim.fn.escape(pat, '\\/.$^~[]')
  end
  return {
    oneshot = false,
    match = function(s)
      return vim.regex(pat):match_str(s)
    end
  }
end
```

You can make a similar generator and `s` to know the length of the line and branch there to add a jump target.

**Comment by jjiangweilan** [comment]
```
local M = {}
local hop = require('hop')
local jump_target = require'hop.jump_target'

local upVal_LastIsEmpty = false
local function HopWordAndEmptyLineImpl()
    return {
        oneshot = false,
        match = function(s)
            if (string.len(s) == 0 and not upVal_LastIsEmpty) then
                upVal_LastIsEmpty = true
                return 0, 1, false
            end
            upVal_LastIsEmpty = false
            return vim.regex('\\(\\k\\+\\)\\|\\(^\\s\\*$\\)'):match_str(s)
        end
    }
end

function M.HopWordAndEmptyLine(opts)
    local generator = jump_target.jump_targets_by_scanning_lines
    upVal_LastIsEmpty = false
    hop.hint_with(
        generator(HopWordAndEmptyLineImpl()),
        opts
    )
end

return M
```
I managed to make this works with an upval to trick the oneshot option. Without it the program will freeze. Hopfully I can get an advice to do it in a "standard" way.
