### ISSUE TITLE
Hop highlights not greyed out for all Markdown elements

### ISSUE THREAD

**Issue by adrian5** [phaazon/hop.nvim#319]
I'm having issues with Hop and the [TokyoNight theme](https://github.com/folke/tokyonight.nvim/issues/238) in that some highlight groups don't get greyed out when firing `require('hop').hint_words()`:

![tokyonight-moon-hop-markdown](https://user-images.githubusercontent.com/5426924/194163530-575fe4a2-b907-4b0b-919c-b53bda169d6f.png)

**nvim** `0.8.0`

**Comment by gilitos92** [comment]
I'm having the same issue, started when upgrading to Nvim 0.8.0.

**Comment by adrian5** [comment]
I'm closing this, it appears to work correctly again. I'm on nvim `0.9.0`.
