### ISSUE TITLE
ignorecase when matching HopChar2

### ISSUE THREAD

**Issue by iqxd** [phaazon/hop.nvim#32]
Can I have case insensitive matching when do HopChar2 ?  
It can save the shift key when matching upper case character,  
so always just two key hits before hit the label key , reduce press error.

**Comment by phaazon** [comment]
Yep, should be doable. :)

**Comment by bscuron19** [comment]
This would be a nice feature for HopChar1 as well.

**Comment by phaazon** [comment]
Fixed by #51. Can you try again and tell me whether your issue is fixed? :)

**Comment by bscuron19** [comment]
Works great! thanks!
