### ISSUE TITLE
would you consider adding HintDirection.{BEFORE,AFTER}_CURSOR_LINE?

### ISSUE THREAD

**Issue by haolian9** [phaazon/hop.nvim#320]
the `*_LINE` i mentioned means when determing the line region for targets, dont consider the current line.
there are HintDirection.{BEFORE,AFTER}_CURSOR already, but they does not suffice my need perfectly.

in my use, i have three keymaps (listed above) for cursor movement, so when
i pressed the rhs, i know where to find my targets.
* sj -> hint_words({direction = AFTER_CURSOR})
* sk -> hint_words({direction = BEFORE_CURSOR})
* sl -> hint_words({current_line_only=true})

the problem is that when i pressed `sj` or `sk` with the `{BEFORE,AFTER}_CURSOR`,
Hop will allocate some marks for the current line, i'd like to avoid that.

so do you think it's worth to have those two directions?

(i have scratched a [commit](https://github.com/haolian9/hop.nvim/commit/017beff36b965e77099b60e0cf37e9b05de7b308) to add them, it does bring in more complexity)

**Comment by phaazon** [comment]
Hm, I don’t quite understand the need honestly. Can you give an exemple?

**Comment by haolian9** [comment]
well, sorry i had not made myself clear, i mean "the result will contain some marks that occupy some key marks like [a-z]" .. " for the current line".

say the currsor lays on `short` in line=3 now, i pressed `sj`,
then Hop allocates some marks for rest words of the current line: "string sequences for which each character represents"
while my real intention was choose a target from `4,$` lines, so the marks for "string sequences for which each character represents" is a waste to me.

```
1 Hop is an EasyMotion-like plugin allowing you to jump anywhere in a document
2 with as few keystrokes as possible. It does so by annotating text in your
3 buffer with hints, >>>short<<< string sequences for which each character represents
4 a key to type to jump to the annotated text. Most of the time, those
5 sequences’ lengths will be between 1 to 3 characters, making every jump target
6 in your document reachable in a few keystrokes.
```

**Comment by haolian9** [comment]
that's the result i want to have when i pressed `sj` in my case.
![5926a5c2-4750-11ed-9695-54b203702c9c](https://user-images.githubusercontent.com/6236829/194728411-e12cb34b-0dc1-4b0a-a3cc-6c6905430d7b.jpg)

(yeah, i forgot i can take a screenshot)

**Comment by phaazon** [comment]
Oh okay, so basically you want a way to discard the current line. Yeah we could merge something like that, indeed. Feel free to open a PR.
