### ISSUE TITLE
shows wrong jump location if search characters in a wrapped line

### ISSUE THREAD

**Issue by iqxd** [phaazon/hop.nvim#33]
**before**    (line 3 is wrapped)
![before](https://user-images.githubusercontent.com/13008913/109975559-b77b9380-7d35-11eb-86cb-af2e75068c5f.PNG)

**:HopChar2**   
 hit search keys '12'

**after**    (wrong jump locations)
![after](https://user-images.githubusercontent.com/13008913/109975806-ff021f80-7d35-11eb-957a-c004d79cf68b.PNG)

**Comment by phaazon** [comment]
That’s odd, I don’t reproduce :/ Have updated recently?

**Comment by phaazon** [comment]
Also, are you using tabs? I have a fix incoming for them, if you happened to be using them.

**Comment by iqxd** [comment]
Thanks for your reply !
I checked the plugin version and my vim config, seems the error is caused by **"set lbr"** , after I comment the setting,  things are working well.

**Comment by phaazon** [comment]
Ah… so I don’t support that yet. Alright then, something else to do! Thanks :D

**Comment by phaazon** [comment]
Can you try again with the latest version of Hop? :)

**Comment by iqxd** [comment]
Updated the plugin, and found it now works pretty well on both lbr and nolbr,
Thanks for you quick fix ,  I really enjoy using the plugin !

**Comment by phaazon** [comment]
Aw thanks for the kind words, I appreciate. Happy you like it!
