### ISSUE TITLE
How can I setup this plugin for matching both the beginning and end of a word

### ISSUE THREAD

**Issue by JuanZoran** [phaazon/hop.nvim#346]
As the title said, I want set the HopWord that can match the beginning of words and end of words

What should I do for that...

**Comment by phaazon** [comment]
You probably want to use `hop.jump_target.jump_targets_by_scanning_line` to create a new Hop mode that uses a regexes matching both the beginning and end of a word. `:h hop-jump-target-api` for more.

**Comment by JuanZoran** [comment]
alright, Thank you for your reply
