### ISSUE TITLE
How do I get hop to work with vscode neovim?

### ISSUE THREAD

**Issue by 55Cancri** [phaazon/hop.nvim#349]
In my init.lua I have:

```lua
require("base") -- general settings
require("highlights") -- colourscheme and other highlights
require("keymaps") -- keymaps
require("plugins") -- plugins
require("hop") -- hop
require("bootstrap") -- packer auto-installer

print("✔ nvim loaded")
print(vim.inspect(package.loaded['hop']))
```

In base.lua, I have:
```lua
local g = vim.g
local o = vim.o
local opt = vim.opt

-- Map <leader> to space
g.mapleader = ' '
g.maplocalleader = ' '
```

In keymaps.lua, I have:
```lua
map("n", "<leader>w", ":HopWord<cr>")
map("n", "<leader>W", ":HopWordMW<cr>")
map("n", "f", ":HopChar1<cr>")
map("n", "F", ":HopChar1CurrentLine<cr>")
```

In plugins.lua, I have:
```lua
-- ...packer setup
  local status, packer = pcall(require, "packer")
  if not status then
    return
  
  end
  
  return packer.startup(function(use)

    use {
        'phaazon/hop.nvim',
        branch = 'v2', -- optional but strongly recommended
        -- config = [[require('hop')]],
        -- config = function()
        -- -- you can configure Hop the way you like here; see :h hop-config
        --   require'hop'.setup {}
        -- end
    }
    
    if packer_bootstrap then
      require("packer").sync()
    end
  end)
```

In hop.lua I have:
```lua
local setup, hop = pcall(require, "hop")

if not setup then
  return
end

hop.setup { keys = "etovxqpdygfblzhckisuran" }
```

And finally I am using the vscode neovim extension. From reddit and other sources, I've heard that some people have managed to get it to work with this extension while others have not.

When I load vscode, I see the following output:
```bash
✔ nvim loaded
true
nil
```

The true is from the init.lua and means that hop was loaded, however, when I then press `<space>w`, I get the error:

```bash
E492: Not an editor command: HopWord
```

which means the hop commands did not load? Please help. I would like an easymotion style navigation flow for vscode neovim where it annotates places to jump to after pressing the spacebar.
Here is the same question on stackoverflow: https://stackoverflow.com/questions/74946509/how-do-i-get-hop-to-work-with-vscode-neovim?noredirect=1#comment132277242_74946509

**Comment by quantumfate** [comment]
You would probably have to fork this project and call `VSCodeSetTextDecorations` where the hints are applied to the ui. You can see that in the easymotion fork for vscode that instead writing to the buffer you will call [](https://github.com/asvetliakov/vim-easymotion/commit/d3c0453b9399f10702f14b487788375f1fb860c6) `VSCodeSetTextDecorations`. But the problem here is that fortunately hop doesn't mess with the buffer at all, so the same steps to integrate hop to vscode like you would in easymotion don't apply here.

**Comment by quantumfate** [comment]
Can you link the other sources you mentioned where people made hop work in vscode? I would like to look into them. I don't think that vscode is a scope of this project but if it works we could at least open a section for vscode in the readme.

**Comment by quantumfate** [comment]
Also note that I think that you are calling the mappings wrong. Can you try 

```
map("n", "<leader>w", "<Plug>(HopWord)")
map("n", "<leader>W", "<Plug>(HopWordMW)")
map("n", "f", "<Plug>(HopChar1)")
map("n", "F", "<Plug>HopChar1CurrentLine)")
```

instead of 

```
map("n", "<leader>w", ":HopWord<cr>")
map("n", "<leader>W", ":HopWordMW<cr>")
map("n", "f", ":HopChar1<cr>")
map("n", "F", ":HopChar1CurrentLine<cr>")
```
If hop really doesn't write to the buffer this might work out of the box as it would send the command directly to neovim.

**Comment by quantumfate** [comment]
Look at my configuration! [See my implementation](https://github.com/quantumfate/quantumvim/blob/easymotion_to_hop/lua/user/vscode/vscode-easymotion.lua). 

I got it to a point where it detects hop and sends the correct commands to neovim but I didn't figure out how to send the commands correctly. Your implementation wouldn't work either as they require parentheses with extra options.

![image](https://user-images.githubusercontent.com/62796852/212064234-c156cead-e7dd-4f8a-9450-5fd8d3d211cf.png)

**Comment by quantumfate** [comment]
Here is a better way to set the keybindings 

```lua
local status_ok, hop = pcall(require, "hop")
if not status_ok then
  return
end

hop.setup {
  keys = 'etovxqpdygfblzhckisuran'
}

local opts = { 
  silent = true, 
  noremap=true,
  callback=nil,
  desc=nil,
}

local keymap = vim.api.nvim_set_keymap
local directions = require('hop.hint').HintDirection

local bindings = {
    { 
      mode = 'n',
      mapping = 'f', 
      desc = '',
      func = function() hop.hint_char1({ direction = directions.AFTER_CURSOR, current_line_only = true }) end
    },
    { 
      mode = 'n', 
      mapping = 'F',
      desc = '',
      func = function() hop.hint_char1({ direction = directions.BEFORE_CURSOR, current_line_only = true }) end
    },
    {
      mode = 'n', 
      mapping = 't',
      desc = '',
      func = function() hop.hint_char1({ direction = directions.AFTER_CURSOR, current_line_only = true, hint_offset = -1 }) end
    },
    {
      mode = 'n', 
      mapping = 'T',
      desc = '',
      func = function() hop.hint_char1({ direction = directions.BEFORE_CURSOR, current_line_only = true, hint_offset = 1 }) end
    },
}


table.foreach(bindings, function(idx, binding) 
  opts.callback = binding.func
  opts.desc = binding.desc
  keymap(binding.mode, binding.mapping, '', opts)
end)
```

**Comment by 55Cancri** [comment]
@quantumfate Sorry I'm late but thank you so much for your response! Out the gate, what you suggested did not work for me at all. However, you inspired me tonight to sit down and redo this nvim config from the ground up, and after some youtube videos and articles, I finally got hop working in vscode.

Some things I had to learn:
- the difference between Plug and packer installers, and how the syntax differs between each.
- splitting files introduces a ton of complexity and misdirection, especially when you are just starting out. Use ONE file.
- you can log lua packages to see which functions can be used

Here is how my barebones nvim.init file looks like:

```lua
local vim = vim

-- use plug instead of packer and assign to variable Plug
local Plug = vim.fn['plug#']
-- install plug.vim using the following command: curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
-- https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim.call('plug#begin', '~/.vim/autoload/plug.vim')
-- install hop
Plug("phaazon/hop.nvim")
vim.call('plug#end')

-- setup hop
local hop = require'hop'
hop.setup { keys = "etovxqpdygfblzhckisuran" }

-- assign hop word highlight to the letter f in all vim modes
vim.keymap.set('', 'f', function()
  hop.hint_words()
end, { remap=true })

-- log all installed lua package including hop to see available functions
print(vim.inspect(package.loaded))
```

Again, thank you so much for your help and willingness to look into this issue and I'm sorry for getting back to you so late!
