### ISSUE TITLE
Highlight is cleared by some colorschemes

### ISSUE THREAD

**Issue by Matts966** [phaazon/hop.nvim#35]
Thank you for this great plugin!

I would like to use `hop.nvim` with some colorschemes, but some colorschemes use `hi clear` before setting colors, and also clear `HopNextKey*` highlights like below.

before

<img width="1440" alt="スクリーンショット 2021-03-07 0 21 07" src="https://user-images.githubusercontent.com/28551465/110211671-04e53580-7edb-11eb-83cc-90468a9d2fd9.png">

after

<img width="1440" alt="スクリーンショット 2021-03-07 0 21 29" src="https://user-images.githubusercontent.com/28551465/110211677-11698e00-7edb-11eb-9e1d-a97f7c15417f.png">

If it is ok, could you please use `autocmd` with `ColorScheme` event, to set `HopNextKey*` after the `hi clear`?

Thank you.

**Comment by cocopon** [comment]
Thank you for using Iceberg!

`hi clear` is the standard way to initialize vim color schemes. Vim has an official color scheme linter and you can see that it checks an existence of this command:
https://github.com/vim/vim/blob/6914e87d3c0387fdcbb117a39e1f6d1fac0ee2e3/runtime/colors/tools/check_colors.vim#L146

I think it may be an issue of `hop.nvim`. For example, `vim-easymotion` defines its highlightings after appling a color scheme by `autocmd ColorScheme *` and it works well:
https://github.com/easymotion/vim-easymotion/blob/d75d9591e415652b25d9e0a3669355550325263d/autoload/EasyMotion/highlight.vim#L141
