### ISSUE TITLE
[Bug] Strange behavior, highlighted character not reset back to original color

### ISSUE THREAD

**Issue by ray-x** [phaazon/hop.nvim#354]
Please refer to the video.

https://user-images.githubusercontent.com/1681295/220627937-02b6491f-4a13-43fb-9326-882cafb6bec0.mp4

**Comment by phaazon** [comment]
Ah… see the pinned issues. That has been around for so long… it’s a bug in Neovim and they never fixed it. There is also a bug with multicursor but I fixed that a while ago as well. I don’t know what to tell you, sorry. :(

**Comment by ray-x** [comment]
Thanks for the response. 
linked issue: https://github.com/phaazon/hop.nvim/issues/57
Close as duplicate
