### ISSUE TITLE
Move to a community for maintenance?

### ISSUE THREAD

**Issue by IndianBoy42** [phaazon/hop.nvim#357]
as I understand it you've moved to Helix, which is cool, but it does leave hop.nvim without a maintainer? it's mostly feature complete but I think having a community for maintenance, updating it for any neovim breaking changes and adding features that people want would be great. 

I'm definitely volunteering to be *one* of the maintainers, it would be a bit of a dick move not to after creating this issue, but I don't know if I have the time to be the sole owner

**Comment by Ultra-Code** [comment]
I second you. Even though I'm also hard on time, I would sacrifice some to see this plugin get into better shape with every neovim release.

**Comment by jdhao** [comment]
this plugin should be continued somehow. It is a pitty to see it fading away like this.

**Comment by brettmitchelldev** [comment]
I'd be happy to pitch in every once in a while as well. As with others, I also don't have a whole lot of time, but I find this plugin really useful and I'd like to help keep it maintained in any way I can.

**Comment by phaazon** [comment]
Yes, I think that if people really want to help and fix the last row/col bugs and keep updated with Neovim, I can provide some write accesses to people interested, as I don’t plan on working on it that much anymore. I’ll probably make an announcement in TWiN.

**Comment by jdhao** [comment]
Thanks for letting us know. Otherwise people are just guessing what happened to this projects 👍

**Comment by quantumfate** [comment]
> 

@phaazon I would love to maintain as well. I'm quite experienced in lua

**Comment by yanshay** [comment]
What's the status with this then?

**Comment by afterlook** [comment]
@phaazon any updates?

**Comment by phaazon** [comment]
Alright, yes, it has been idle for way too long and I don’t have time to work on it, nor fix the bugs. Looking at the forks, there is [@smoka7’s](https://github.com/smoka7/hop.nvim). I had a look at the commits and I think the community should go along with them.

This is an open source community, and yes, I don’t plan on working on hop.nvim anymore, and I’m happy to see that people still want to maintain it and make it thrive (I very oftentimes miss it when working in other editors). I’ll update the README to redirect people to the fork of @smoka7 for now.

**Comment by phaazon** [comment]
By the way, I think it’s worth it to mention to @codicocodes the fork so that people reading TWiN can see the new place to go to.
