### ISSUE TITLE
new fork

### ISSUE THREAD

**Issue by smoka7** [phaazon/hop.nvim#369]
I've forked the repo [here](https://github.com/smoka7/hop.nvim) and intend to maintain it going forward. I've already merged some pull requests and implemented new features. Feel free to use or contribute if you're interested.
Added fixes and features:
- HopCamelCase
- HopYank
- HopPaste
- Inline hints
- Exclude buffers by file types
- Invalid Col bug fix
- Invalid win id bug fix
- Exclude the current line in hints
- Empty line bug fix

**Comment by jdhao** [comment]
Maybe after some time, every hop user use their own fork

**Comment by TD-Sky** [comment]
Have you read this [issue](https://github.com/phaazon/hop.nvim/issues/357#issuecomment-1554676879)? phaazon said he was willing to give write access to new maintainer.

**Comment by jdhao** [comment]
I know that issue, but no action is done :(

**Comment by TD-Sky** [comment]
> I know that issue, but no action is done :( I have a PR sitting for too long， maybe I need to use my own fork or use Leap.nvim instead.

Cause the person who issued originally may give up to maintain now. I suggest you to contact phazzon via twitter.

**Comment by smoka7** [comment]
@jdhao If you've decided to create a fork, ping me if you want it to work on it together.

**Comment by quantumfate** [comment]
> @jdhao If you've decided to create a fork, ping me if you want it to work on it together.

Hey I would also love to help! Hop is a really essential part of my workflow and I can't afford it to cave in lmao

**Comment by TD-Sky** [comment]
Are you willing to maintain this project if phaazon give you the permission?

**Comment by smoka7** [comment]
At first, I wanted to ask him about it, but after [this](https://www.reddit.com/r/neovim/comments/142buyl/comment/jn58297/?context=3) I doubt that he will give write permission to someone who doesn't know.

**Comment by TD-Sky** [comment]
> At first, I wanted to ask him about it, but after [this](https://www.reddit.com/r/neovim/comments/142buyl/comment/jn58297/?context=3) I doubt that he will give write permission to someone who doesn't know.

Got it. Thanks for your reply.

**Comment by phaazon** [comment]
Thank you @smoka7. I think the community should along with your fork, given the time and work you’ve put in.

I will update the README to redirect people to your fork.

**Comment by smoka7** [comment]
Thanks @phaazon, You've done a great job with hop. I hope you have a good life ahead.

**Comment by phaazon** [comment]
Thank you @smoka7 for following-up!
