### ISSUE TITLE
checkhealth error!

### ISSUE THREAD

**Issue by StrTzz123** [phaazon/hop.nvim#377]
- ERROR Failed to run healthcheck for "hop" plugin. Exception:  
- function health#check, line 25   Vim(eval):E5108: Error executing lua ~/.local/share/nvim/plugged/hop.nvim/lua/hop/health.lua:13: attempt to index field 'opts' (a nil value)  
stack traceback:   ~/.local/share/nvim/plugged/hop.nvim/lua/hop/health.lua:13: in function 'check'   [string "luaeval()"]:1: in main chunk

**Comment by phaazon** [comment]
Please go to the fork instead; I do not maintain `hop.nvim` anymore.
