### ISSUE TITLE
Doesn't work in terminal mode

### ISSUE THREAD

**Issue by breneser** [phaazon/hop.nvim#381]
The plugin doesn't seem to work in terminal mode. On a normal buffer when in insert mode, it works fine and jumps to where I want. But when in terminal mode, I get the following error:

```shell
E5108: Error executing lua vim/_editor.lua:0: nvim_exec2(): Vim(normal):Can't re-enter normal mode from terminal mode
stack traceback:
	[C]: in function 'nvim_exec2'
	vim/_editor.lua: in function 'cmd'
	.../B.Eser/.local/share/nvim/lazy/hop.nvim/lua/hop/init.lua:425: in function 'refine_hints'
	.../B.Eser/.local/share/nvim/lazy/hop.nvim/lua/hop/init.lua:387: in function 'hint_with_callback'
	.../B.Eser/.local/share/nvim/lazy/hop.nvim/lua/hop/init.lua:310: in function 'hint_with'
	.../B.Eser/.local/share/nvim/lazy/hop.nvim/lua/hop/init.lua:605: in function 'hint_lines_skip_whitespace'
	[string ":lua"]:1: in main chunk
```
Highlights show up correctly, but once picked, I get the error above.
To re-produce, map `HopChar1` command in terminal mode and try jumping to character using the shortcut.

**Comment by hadronized** [comment]
I need to archive the repository, as I don’t work on it anymore. It’s been months if not years. Sorry.
