### ISSUE TITLE
behavior on consecutive same characters

### ISSUE THREAD

**Issue by wkcosmology** [phaazon/hop.nvim#43]
**Problem description:**
When I jump to consecutive same characters, like
`ssss`
the hint key will be, for example
`ga, gb, gc, gd`
but I can only see
`ggggd`
and I need to input `g` before I can get the second hint for the first three `s`.

This is frustrating because I need to press the key, read, and press another key.

**Suggestion:**
My suggestion is that, when you render the characters on a line, you can render it backward. Then we will see
`gabcd`
and one can just jump to the destination.

This can also be an option for users to make their choice.

**Potential problem:**
There is one potential problem. The plugin should ensure that the consecutive same characters must have same first hint. Otherwise, we cannot make effective jump.

**Comment by phaazon** [comment]
This situation happens with `:HopChar1`or `:HopPattern` (it can also happen with `:HopChar2` with 3-sequence but unlikely). It is true that the `gggggg` situation is not ideal (but the current situation is correct, though, as we don’t lose anything; the hints are just hidden).

What you describe _could_ be implemented but I’m not sure it would be any better. Imagine the following:

```
ggggggggggggk
        ^ you want to jump here
```

If we replace this by (assuming the right highlight):

```
gabcdefghijk
        ^ you want to jump here
```

Then we now have to look at the first key to type, which is at a different location than where you want to jump to:

```
v you first need to look at this key and type it
gabcdefghijk
        ^ while you wanted to jump here
```

Worse, imagine you don’t have any key to cover the whole thing: you’re going to have duplicates and we get the same initial problem (so do we run this recursively in that case?). Given the complexity of such a situation, and — at least to my knowledge — the very low frequency at which people will hit such a situation, I’m not sure it’s worth it. :slightly_smiling_face:

**Comment by wkcosmology** [comment]
@phaazon You are absolutely right.

I saw this behavior in easymotion, and I though it is convenient for two or three consecutive same characters.
But their behavior becomes weird when there is a long sequence of same characters.

Now I think your way might be better.

Thanks for the patient reply. Appreciate your work!

**Comment by phaazon** [comment]
I’m going to close this as I think the current situation is the best tradeoff. Feel free to comment further if you’d like to re-open.
