### ISSUE TITLE
When using HopPattern, nvim turns into unresponsive after pressing Esc to quit HopPattern.

### ISSUE THREAD

**Issue by pittcat** [phaazon/hop.nvim#44]
https://user-images.githubusercontent.com/22888402/111020200-12c91800-83ff-11eb-93c1-790945e159cf.mp4

**Comment by phaazon** [comment]
Yep, I reproduce. Thanks, I’ll try to fix that asap.

**Comment by phaazon** [comment]
@pittcat it’s fixed now. Thanks for the feedback, please tell me whether things look great on your side, and feel free to close the issue.

**Comment by pittcat** [comment]
Thank you for your reply and for all your efforts on hop.nvim
