### ISSUE TITLE
Hopping leaves behind apostrophe character (Possibly related to remap)

### ISSUE THREAD

**Issue by Kyran-C** [phaazon/hop.nvim#49]
Hey, love this plugin! 

I've noticed that when hopping (using single letter or word mode) it leaves an apostrophe at the location where the cursor was. The apostrophe is actually in the text, not just a virtualtext rendering bug.

I tried running `:HopWord` just to make sure it wasn't anything funky with my keybinds but it still happens. I uninstalled every other plugin except hop.nvim to rule out any strange conflicts but no change.

What I suspect is happening is when hopping, it's calling a vim command without the noremap flag set, which is then using my own keymap. And since I'm a savage animal who remapped `m` to `a` it ends up inserting an apostrophe rather than creating a mark as intended.

```
Neovim version: v0.5.0-dev+1165-ge5bef5974
```

**Comment by phaazon** [comment]
Thanks for the feedback. Given your description of the bug, I think we should merge your PR and see whether there is a better solution later. I’ll keep that in mind.
