### ISSUE TITLE
Jump to the line

### ISSUE THREAD

**Issue by Shatur95** [phaazon/hop.nvim#5]
EasyMotion have the ability to jump to specific line. It would be great to have a similar feature in this plugin :)

**Comment by phaazon** [comment]
It’s really easy to do but I have a question: do we really need it? Do people really use this? But I can add it tonight if people think it is useful.

**Comment by Shatur95** [comment]
I often use this when I want to get to the beginning of a line. This usually requires fewer presses since there are fewer lines than words.

**Comment by phaazon** [comment]
That makes sense. I’ll add it as soon as I can. :)

**Comment by phaazon** [comment]
This is now implemented. Have fun and don’t put too many emojis in your buffers, please.

**Comment by Shatur95** [comment]
Thank you!
