### ISSUE TITLE
[Feature] Incremental Search for HopPattern?

### ISSUE THREAD

**Issue by bscuron** [phaazon/hop.nvim#52]
Is it possible to do an incremental search for HopPattern? So as you are typing in the pattern, what is being matched is being highlighted in the current buffer.

Thanks!

**Comment by phaazon** [comment]
Yes I want that as well. I need to check how to do that.

**Comment by bscuron19** [comment]
> Yes I want that as well. I need to check how to do that.

sounds good thanks!

**Comment by bscuron19** [comment]
I was wondering if there are any updates on this feature?

**Comment by phaazon** [comment]
Not really, I haven’t been able to find any way to make it happen. I’m not sure there’s a callback mechanism to allow for that, but I might be wrong.

**Comment by jemag** [comment]
https://github.com/haya14busa/incsearch-easymotion.vim has a similar feature. Not sure if it could provide some ideas regarding the implementation.

For me this is the only thing missing from Hop, HopPattern works really well but I really miss the incremental highlighting

**Comment by jemag** [comment]
In the meantime, I am using this:
```lua
vim.api.nvim_set_keymap('c', '<C-f>', "<cr><cmd>lua require'hop'.hint_patterns({}, vim.fn['getreg']('/'))<cr>", {noremap = true})
```
which works pretty well and allows you to press "Ctrl-f" while in the search prompt to show the hints to reach any of the search results.

**Comment by darzok0914** [comment]
Hey, I was just reading through the issues and randomly came across this thread. Few weeks ago I started working on a personal project and I was able to code a bit of lua to hook into the command line. I was able to intercept cmds like / ? And : and know what the user is typing in real time. Let me know if you are still interested

**Comment by dataO1** [comment]
Definitely still interested in this!

**Comment by spost-stateless** [comment]
Hey @darzok0914 , I'm interested in taking a whack at this in my spare time, could you share your code?

**Comment by pascalporedda** [comment]
I would love to see this as well.

**Comment by phaazon** [comment]
This was done in #236.
