### ISSUE TITLE
behavior on quit

### ISSUE THREAD

**Issue by wkcosmology** [phaazon/hop.nvim#54]
**Problem**:
First I perform the search `:HopChar1`
Then I quite though `<esc>`
The highlight of the last line will be faint (just like the highlight for non-target characters in hop)

**Comment by phaazon** [comment]
Can you post an image? I don’t reproduce.

**Comment by wkcosmology** [comment]
**Behavior:**
![render1616680410175](https://user-images.githubusercontent.com/29885814/112484953-c95ac000-8d50-11eb-93ec-04268f974000.gif)

**Config:**
call plug#begin('~/.vim/plugged')
  Plug 'phaazon/hop.nvim'
  Plug 'sainnhe/edge'
call plug#end()
set cmdheight=2
syntax enable
set background=dark
set signcolumn=yes
set shortmess+=c
set nocursorcolumn
set noshowmode
set conceallevel=0
set termguicolors
set shiftwidth=4
syntax enable
let g:edge_transparent_background = 1
colorscheme edge

**vim --version**:
NVIM v0.5.0-dev+bda12927b
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210302-18260-303fhb/build/config -I/tmp/neovim-20210302-18260-303fhb/src -I/usr/local/include -I/usr/local/opt/luv/include -I/opt/local/include -I/tmp/neovim-20210302-18260-303fhb/build/src/nvim/auto -I/tmp/neovim-20210302-18260-303fhb/build/include
Compiled by wangk@Kosmos

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-bda1292_1/share/nvim"

Run :checkhealth for more info

**Comment by aeosynth** [comment]
Maybe the same issue, if I do `:HopWord` + `<C-C>`, I return to normal mode but the highlights don't disappear and I can't get rid of them, calling hop again gives a warning about opening hop within hop.

**Comment by wkcosmology** [comment]
> Maybe the same issue, if I do `:HopWord` + `<C-C>`, I return to normal mode but the highlights don't disappear and I can't get rid of them, calling hop again gives a warning about opening hop within hop.

I can produce this problem, too. I have to delete the buffer to solve this problem.

**Comment by phaazon** [comment]
Yep, I just reproduced. Thanks, I’m going to fix it right now, it’s annoying.

**Comment by phaazon** [comment]
Should be fixed now. Can you peeps pull updates and tell me whether it’s okay for you? :)

**Comment by wkcosmology** [comment]
> Should be fixed now. Can you peeps pull updates and tell me whether it’s okay for you? :)

Yes. The problem is fixed now! Thanks!
