### ISSUE TITLE
smart case feature

### ISSUE THREAD

**Issue by timsofteng** [phaazon/hop.nvim#55]
Is it any way to enable something like smart case in Hop2chars?
I mean when i print two characters in lowercase then hop should find all uppercase and lowercase results. But when I print one or both characters in uppercase it should find exact results.

**Comment by phaazon** [comment]
Hello. This is now implemented. Feel free to update and tell me what you think. Hop will respect the `smartcase` behavior — it has to be set globally, though. A specific override could be implemented but I think people will likely to have the same behavior as the global one so I’ll start with that.

**Comment by timsofteng** [comment]
Yep. I agree that it's good idea to bind it to global search method.

I've test it and it worls perfectly.
Thanks!
