### ISSUE TITLE
hard to distinguish between q and g with underline

### ISSUE THREAD

**Issue by iqxd** [phaazon/hop.nvim#70]
when set fonts like JetBrains Mono and Hack ,  etc 

Hack Font:
![image](https://user-images.githubusercontent.com/13008913/115019471-d439e800-9eeb-11eb-89ba-e5bf16cf8bc3.png)

JetBrains Mono:
![image](https://user-images.githubusercontent.com/13008913/115019894-5fb37900-9eec-11eb-85e9-82c5d16c15e2.png)

**Comment by pockata** [comment]
Hey @iqxd, I also use JetBrains Mono and had a similar issue.
I solved it by changing the `keys` configuration to remove `q` and `o` and leave only `g` and `p` by doing
```lua
require'hop'.setup({
	keys = 'asdghklwertyuipzxcvbnmfj',
})
```

**Comment by iqxd** [comment]
Thanks @pockata , it helps on this issue currently .
However, I think it's better if  there's an option to disable/enable underlined on key chars.

**Comment by phaazon** [comment]
Hey, you can change all the highlights, no need to switch the keys for that. We can change the default highlights by removing the underline if people think it’s too disturbing.

**Comment by pockata** [comment]
Thanks, @phaazon, I just looked at the highlight groups in the source code and setting `highlight HopNextKey gui=bold` removes the underline (defaulting to `gui=bold,underline`). Now there's no need to alter the `keys` configuration.

Perhaps documenting the highlight groups in the README/help files so users know they can easily change the look of Hop?

**Comment by phaazon** [comment]
Yeah the autocommand will remove and replace them. The joy of theming in Neovim.

**Comment by phaazon** [comment]
I removed the underline, it was a bad default, and documented how to customize the highlights. I’ve also allowed people to disable the autocommands.
