### ISSUE TITLE
Some hints are not shown when special characters are present

### ISSUE THREAD

**Issue by tmwitczak** [phaazon/hop.nvim#72]
__Non-ASCII characters, when present in a line, cause hints to disappear from the end of the line.__

They seem to only affect hints shown after the Unicode character and it looks like every occurrence of the extended char shortens the line that is seen by 2 characters.

For example:
![image](https://user-images.githubusercontent.com/44136266/116310515-65417680-a7aa-11eb-9422-1ab44fc2a188.png)

:HopChar1 with 'd' pressed
![image](https://user-images.githubusercontent.com/44136266/116310611-8904bc80-a7aa-11eb-9c33-d2b79ed9313a.png)

Line starting with an additional extended quote character (:ascii -> _<’> 8217, Hex 2019, Oct 20031, Digr '9_)
:HopChar1 with 'd' pressed
![image](https://user-images.githubusercontent.com/44136266/116311314-6921c880-a7ab-11eb-8f76-0b89a8479908.png)
We can see the last hint for 'd' hasn't appeared.

:HopChar1 with 'c' pressed
![image](https://user-images.githubusercontent.com/44136266/116311367-78087b00-a7ab-11eb-84d1-65c610abcdc4.png)
Likewise, the hint for 'c' is not there.

:HopChar1 with 'b' pressed
![image](https://user-images.githubusercontent.com/44136266/116311559-a9814680-a7ab-11eb-9a18-2f709e2bd41a.png)
Hints are shown correctly.

Line starting with two extended characters.
:HopChar1 with 'b' pressed
![image](https://user-images.githubusercontent.com/44136266/116311866-109efb00-a7ac-11eb-82c9-2436840c32bb.png)
The last hint is not shown.

For every non-ASCII character added in the line, some hints are dropped from the end of the line. It seems that every special char accounts for additional two missed columns.

:HopChar1 with 'd' pressed
![image](https://user-images.githubusercontent.com/44136266/116312689-0f220280-a7ad-11eb-9407-3ee141b97fcb.png)
When lines are wrapped, the problem is non-existent.

Line ending with special characters / in the middle of the line.
:HopChar1 with 'd' pressed
![image](https://user-images.githubusercontent.com/44136266/116312860-4e505380-a7ad-11eb-8962-4fa7eb65e20f.png)
![image](https://user-images.githubusercontent.com/44136266/116313225-c7e84180-a7ad-11eb-8d42-dbf3da54875f.png)
The problem only seems to affect hints that should be placed after the special characters in the line.

Screens are from my usual config, but I've checked this on an empty config with only the plugin loaded – the bug is still there.

_nvim version: NVIM v0.5.0-dev+1281-gecf075eb2_

**Comment by phaazon** [comment]
I tried to reproduce and couldn’t. Do you happen to use `virtualedit`, `wrap` or that kind of options?

**Comment by phaazon** [comment]
Woooooooooooooop. Reproduced with `wrap`. Thanks for reporting, I’m having a look.

**Comment by phaazon** [comment]
This is now fixed, @tmwitczak. Can you test after updating? Thanks!

**Comment by tmwitczak** [comment]
Works like a charm. Thank you!
