### ISSUE TITLE
Incorrect hint labels when hint keys include non-ASCII characters

### ISSUE THREAD

**Issue by maxigaz** [phaazon/hop.nvim#73]
In Neovim v0.5.0-dev+1291-gb227cedf8, hop doesn't show the corrent hint label for a key if that key is a non-ASCII character.

For example, this is what I've added to my `init.vim`:

```
lua require'hop'.setup { keys = 'asdfhjkqweruiopyxcvbnmlé' }
```

Notice the final character, `é`. This is on a Hungarian keyboard, at the same position as `;` is on US layouts.

With this in place, when I run `:HopChar1` and press `a`, `<c3>` and `<a9>` are shown at several places, like in the screenshot:

![neovim-hop-key1](https://user-images.githubusercontent.com/10419911/116906865-14fe6480-ac41-11eb-8aa0-ce5ffbdd720e.png)

If I change `é` to something else, such as `g`, all hints are displayed normally.

![neovim-hop-key2](https://user-images.githubusercontent.com/10419911/116906939-35c6ba00-ac41-11eb-9f0e-a9d9efac6218.png)

**Comment by phaazon** [comment]
@maxigaz can you check again after updating? It’s now fixed. :)

**Comment by maxigaz** [comment]
Yes, I can confirm that it's working now. Thank you very much!
