### ISSUE TITLE
Space and punctuation trigger case sensitive search

### ISSUE THREAD

**Issue by jghauser** [phaazon/hop.nvim#74]
First of all, thanks a ton for this plugin! It's so much better/faster than easymotion and sneak.

The problem I came across is that given this text:

`This test. A test.`

Jumping to ` a` (that is, space+a) gives no results, only jumping to ` A` (that is, space+A) does. At least to me this is highly counterintuitive. Space shouldn't trigger smart case-sensitive search.

EDIT: The same seems to obtain for punctuation.

**Comment by phaazon** [comment]
Do you jump to `a` or to ` a`?

**Comment by phaazon** [comment]
This is an interesting issue. I’m having a look, thanks! Also, it looks like the hints are ill-placed (probably because of trimming).
