### ISSUE TITLE
Todo comments interfers with Hop

### ISSUE THREAD

**Issue by folke** [phaazon/hop.nvim#76]
Hi, author of [todo-comments](https://github.com/folke/todo-comments.nvim) here.

I use the highlights api to highlight todo comments, but it seems that whenever hop is started, the colors [don't get dimmed](https://github.com/folke/todo-comments.nvim/issues/5) as you can see in the screenshot below:
![image](https://user-images.githubusercontent.com/292349/118362995-1dab4080-b547-11eb-98e7-9f870b26029c.png)

Is there anything I can do to fix this?

Probably also related to #75

**Comment by monkoose** [comment]
Author of #75 here.
Hop uses `vim.api.nvim_add_highlight()` to dim all visible text. And this function doesn't have an priority parameter. But by default it's priority set to 4096 (why there are no such parameter for that it the question to neovim contributors). Max highlight priority value is (2 ^ 16) - 1 = 65535. I didn't check how you set up highlights for your todo plugin. But maybe you can use `vim.api.nvim_buf_set_extmark()` and set value of `priority` key of the `{opts}` table below 4096.

But matched brackets/parentheses use like some built-in nvim/vim mechanism to highlight things. And you can't override them even with the highest priority value.

**Comment by folke** [comment]
@monkoose  This Hop code can be optimized to do in one call instead of multiple highlights per line. It would also solve my issue:
```lua
	vim.api.nvim_buf_set_extmark(buf_handle, hl_ns,top_line, 0, {
		end_line = bottom_line,
		hl_group = "HopUnmatched",
		hl_mode = "replace",
		hl_eol = true
	})

```

**Comment by monkoose** [comment]
I think you asked on your side.
But yes, `hl_mode = "replace"` should work too in theory.

**Comment by folke** [comment]
@monkoose you're right, I can probably fix it on my end by lowering the priority. Thanks!

**Comment by monkoose** [comment]
@folke is it actually right to do it on your side? I'm not sure. I think a lot of plugins will use or already use `nvim_add_highlight()`. So it is better on hop side to increase its highlight groups priorities.

**Comment by folke** [comment]
That on-replace code should work. I'm working on a new plugin that also does some dimming on the screen using that method.

**Comment by monkoose** [comment]
So the documentation is outdated?

**Comment by phaazon** [comment]
I haven’t looked into priorities for extmarks yet, but I plan to (I got similar feedback from people using indent guidelines for instance). I’ll come back to you when I have time to work on this. But yes, I do need to figure that priority thing out. Someone made a PR lately but I didn’t get any explanation about the priorities and I don’t want to merge something I don’t understand fully yet. I guess it’s just a “higher priority wins” game but I want to know the rules first. :wink:
