### ISSUE TITLE
Doesn't work with foldtext

### ISSUE THREAD

**Issue by metalelf0** [phaazon/hop.nvim#78]
Hi, I'm not sure this is doable with your current architecture, but a feature I'd love to see is being able to hop to folded text.

Say I've a big class, with a lot of methods (yeah, it happens). Sometimes my approach is to set a low foldevel and jump and expand only the methods I wanna see. If I try to hop to text inside the foldtext (I mean the text that is displayed on screen, not the folded one, obviously) then I can't "land" on it.

Hope this is clear enough, if it isn't I'll try to provide an example.

Thanks!

**Comment by bscuron19** [comment]
@metalelf0 

nnoremap { zkzz
nnoremap } zjzz

You might find zk and zj useful. They will take you to the next fold.

**Comment by donkeyboy666** [comment]
I have similar issue, my config. It looks like algorithm places permutations on all lines, but they are hidden in folds, so you get long sequences like the folded left...

```
require'hop'.setup{ 
  keys = 'riockpqmaust', 
}
```



![2021-07-15_00-04](https://user-images.githubusercontent.com/74857642/125699424-26d8b4d1-e309-46bf-abac-d32b7ece8f58.png)

**Comment by phaazon** [comment]
A PR was merged lately to fix that. #222.
