### ISSUE TITLE
Unable to use other keys like h,j,k,l to cancel hints

### ISSUE THREAD

**Issue by akinsho** [phaazon/hop.nvim#8]
Hi thanks for this great plugin 👍🏿 really enjoying it so far.

I was wondering if there is a way to cancel a jump while inputting characters with keys other than `<esc>`. Atm if I use the following steps I get unpredictable behaviour.
1. trigger `hint_char1` via `lua require('hop').hint_char1{winblend = 100, keys = 'asdgqwertyuiopzxcvbnmf'}`. NOTE: `h,j,k,l` have been removed from the keys
2. press `h,j,k,l` neither of these keys will put you on the line that the command would usually take you to, they don't just deactivate `hop` either like `<esc>` does. Instead they jump you somewhere seemingly random.

My use case for this functionality is that I often start trying to jump somewhere, historically with `vim-sneak` and I change my mind before entering the character and instead want to just go somewhere else or stay where I am more or less so I just _move_ out of the `sneak` hint thing

**Comment by phaazon** [comment]
Hi,

Yep, that’s definitely a valid use case and so far, no, unfortunately, there’s no way to do it but I’d like that added. I’ll work on it. Thanks for reaching out!
