### ISSUE TITLE
Highlighting is broken in the latest commit

### ISSUE THREAD

**Issue by rebuilt** [phaazon/hop.nvim#87]
Hello, thank you for your plugin.  It's amazing.

Highlighting has broken for me in the latest commit.  The broken highlighting looks just like the images posted on this issue https://github.com/phaazon/hop.nvim/issues/35

Reverting to commit e5eb06d fixes the issue

I've tested with the following colorschemes
- https://github.com/sainnhe/sonokai
- https://github.com/ChristianChiarulli/nvcode-color-schemes.vim
- https://github.com/navarasu/onedark.nvim

**Comment by phaazon** [comment]
Have you updated? That commit doesn’t have anything to do with the broken highlightings, so I suspect something is not setup correctly on your side?

**Comment by phaazon** [comment]
Do you call `require'hop'.setup { … }` somewhere? Highlights and autocommands are set from there.

**Comment by rebuilt** [comment]
Thanks.  I accidentally commented out the setup line.  It's strange that the previous commit worked without the setup function.  Maybe the previous packer_compiled entry for hop was still valid?
