### ISSUE TITLE
Normal mode is switched on when trying to use visual extension

### ISSUE THREAD

**Issue by maxigaz** [phaazon/hop.nvim#89]
Using Neovim v0.5.0-dev+1372-g056c464e8, I can't get visual extension to work.

Minimal `init.vim`:

```vim
let $PLUGIN_DIRECTORY = '~/.local/share/nvim/plugtest'
packadd hop.nvim

xmap f :lua require'hop'.hint_char1()<CR>
xmap F :lua require'hop'.hint_char1({ 'extend_visual' }, { 'true' })<CR>
```

With that, when I press `f` in visual mode and press a hint key, normal mode is activated as I jump to the new location.

I've tried passing the option `extend_visual` because it was mentioned [here](https://github.com/phaazon/hop.nvim/issues/28#issuecomment-789333433), although I can't find any information on this in the documentation, only in older commits.

Am I missing something?

**Comment by tafryn** [comment]
I get the same behavior. Seems like hop's visual extend functionality isn't working correctly.

**Comment by bscuron19** [comment]
map s <cmd>HopChar1<CR>

**Comment by bscuron19** [comment]
```map s <cmd>HopChar1<CR>```

**Comment by maxigaz** [comment]
> `map s <cmd>HopChar1<CR>`

Thank you for the advice! I've just tried `<cmd>HopChar1<CR>` and it does work in visual mode.

Although I still wonder why it doesn't work when the lua functions are called directly.
