### ISSUE TITLE
Can not quit the search mode if there is no pattern word

### ISSUE THREAD

**Issue by fgheng** [phaazon/hop.nvim#9]
Hello, while I used HopChar1 to search a word, problems occurred. 
I don't know how to quit the search mode if there's no character of my search.

I search 'a', but there is no 'a' in the current window.
![image](https://user-images.githubusercontent.com/50551377/108014389-bc0f2f00-7048-11eb-852d-0dc0d0b3f07a.png)

**Comment by phaazon** [comment]
You can simply hit `Escape` right now to quit this mode. Also, I think I should handle this and automatically move the user out of the hint mode. Thanks for reporting.

Oh and, you can also remap a key to quit Hop, but that’s not currently documented, so I’ll tell you when documentation is okay for this.

**Comment by fgheng** [comment]
thanks for your hard work.
