### ISSUE TITLE
Marks displaying changed

### ISSUE THREAD

**Issue by timsofteng** [phaazon/hop.nvim#90]
Hello. After some of updates I notice marks of `hop` changed from good visible red to almost unvisible white.
Is it knowing issue?
![image](https://user-images.githubusercontent.com/51912173/120868206-2f0ec800-c59c-11eb-9489-7eb240743b8f.png)

**Comment by rmagillxyz** [comment]
I was having the same issue. I was able to fix this by adding the highlight groups to my colorscheme. Check out `:help hop-highlights` for the list. Looks like there is also an autocmd you can use to automatically set them.

**Comment by rmagillxyz** [comment]
> Hello. After some of updates I notice marks of `hop` changed from good visible red to almost unvisible white.
> Is it knowing issue?
> ![image](https://user-images.githubusercontent.com/51912173/120868206-2f0ec800-c59c-11eb-9489-7eb240743b8f.png)

I was having the same issue. I was able to fix this by adding the highlight groups to my colorscheme. Check out `:help hop-highlights` for the list. Looks like there is also an autocmd you can use to automatically set them.

**Comment by Julpikar** [comment]
I fixed this issue by calling highlighting directly after calling colorscheme.
```
use {
    "Julpikar/onedark.nvim",
    config = function()
      vim.g.onedark_style = "darker"
      require("onedark").setup()
     local highlight = require'hop.highlight'
  highlight.insert_highlights()
    end
  }
```

**Comment by phaazon** [comment]
Ah yes, this is an intentional change. Ideally, we should be using a declarative layer (I’m working on one) so that people don’t have to call the `setup` function and code their configuration, but for now we have to. Sorry for the inconvenience, it wasn’t planned in the first place to make it work out of the box magically 😕 .
