### ISSUE TITLE
Background transparency don't change when activate hop to move to word

### ISSUE THREAD

**Issue by jordisantamaria** [phaazon/hop.nvim#92]
Before, when I activate hop to jump to a word or a letter, code change transparency, so It was easier to see where to jump, right now background keeps the same and text is white, so It becomes harder to jump... and If code is white also... It becomes even harder...

https://gyazo.com/78f82192967d6ff7f835e1a0f0eeaee6

Is It possible to have It working as before?

**Comment by mirsella** [comment]
I got the same problem, i don't know if it's intentional, but now the shortcut are not highlighted like before.

**Comment by mirsella** [comment]
i've tracked down the commit and 7eefd95ff1cd5a0189904a70763f0141a6be5d11 is responsible

**Comment by jordisantamaria** [comment]
> i've tracked down the commit and [7eefd95](https://github.com/phaazon/hop.nvim/commit/7eefd95ff1cd5a0189904a70763f0141a6be5d11) is responsible
> 
> in my case, [e5eb06d](https://github.com/phaazon/hop.nvim/commit/e5eb06d6f3caff15f3abd35c6c21135f93fa4eb7) work but everything after doesn't work, and the one right after the last known working is [7eefd95](https://github.com/phaazon/hop.nvim/commit/7eefd95ff1cd5a0189904a70763f0141a6be5d11)
> 
> @jordisantamaria in the meantime if you use plug as a plugin manager you can use this line `Plug 'phaazon/hop.nvim', { 'commit': 'e5eb06d6f3caff15f3abd35c6c21135f93fa4eb7' }` to use the last working commit

I see, thanks you.

**Comment by snezhniylis** [comment]
7eefd95 makes it a requirement to call `hop.setup` by moving highlight injecting code inside this function. If it's intentional, this should be documented. Also
```lua
if opts.create_hl_autocmd then  
  highlight.create_autocmd()
end
```
should check for `M.opts` instead of `opts`.

For now, to make it work. Put the following in your config:
```lua
require('hop').setup({create_hl_autocmd = true})
```

**Comment by phaazon** [comment]
`create_hl_autocmd` [is set by default](https://github.com/phaazon/hop.nvim/blob/master/doc/hop.txt#L522), but yes, you need to at least call `setup` now.

**Comment by mirsella** [comment]
is there a way to call setup in init.vim instead of init.lua ?

**Comment by ggandor** [comment]
> 
> 
> is there a way to call setup in init.vim instead of init.lua ?

Yes, just wrap the call like this:
```
lua << EOF
  ...
EOF
```
See `:h :lua-heredoc`.

**Comment by snezhniylis** [comment]
> `create_hl_autocmd` [is set by default](https://github.com/phaazon/hop.nvim/blob/master/doc/hop.txt?rgh-link-date=2021-06-19T12%3A29%3A25Z#L522)

It is, but `setup` [looks up](https://github.com/phaazon/hop.nvim/commit/7eefd95ff1cd5a0189904a70763f0141a6be5d11#diff-5dc228ff2a63872d5d004af9e04cf49da68ee817118c9103347437f04e1675acR243) `create_hl_autocmd` in `opts` which is passed as an argument, and not `M.opts` where it is set. This causes `highlight.create_autocmd()` to never get called if `create_hl_autocmd` is not set directly. I'll PR a fix.
