### ISSUE TITLE
Create a HopMark command?

### ISSUE THREAD

**Issue by winston0410** [phaazon/hop.nvim#94]
I have used the source of hop(great reference!) and built a plugin that will show mark and jump to it

https://github.com/winston0410/mark-radar.nvim

I think this feature can be integrated in hop with a command called `HopMark`. What do you think about this feature? If this looks good to you I can port those code from there to hop and create a PR.

**Comment by phaazon** [comment]
Interesting idea, that could indeed be integrated, and shouldn’t be too hard. It would probably require to get the list of marks for the current buffer, filter them using the current view (lines and colums), and mark those.

**Comment by winston0410** [comment]
Yes indeed. Well then I will try and make a PR for this, thanks

**Comment by Alekhine51** [comment]
I don't fully understand what this does, even after watching the video on your page. What exactly is a mark in this context?

**Comment by phaazon** [comment]
Closing for stall issue. Two possible continuations here:

1. You can now create a Hop extension (`:h hop-extension`) and share your extension!
2. If the extension is simple and is justified to be merged upstream here, you can open a PR referencing this issue.

Thank you.
