### ISSUE TITLE
Wrong hints

### ISSUE THREAD

**Issue by monkoose** [phaazon/hop.nvim#96]
Not sure how to title this issue.
Hop can show hints in wrong places (there are no char) and not showing correct ones. Seems like all problems cause of how vim `help` files structured, and how Hop process currently visible chars on the screen.

Way to reproduce `:h getpos()` then `8zl` to shift screen right, then look for `g` with `HopChar1`. Here is a screenshot
![Hop](https://i.imgur.com/miDbigN.png)

There are nothing to show for `h` and `k` and there are no hint for g in `getcurpos()` `getpos()` `getpid()`

**Comment by phaazon** [comment]
This is a super weird bug. I can reproduce with what you describe but I can’t figure out how to reproduce in the general case. Also, this seems to be valid only for `nowrap`, since you are using `zl`. It might be a multi-byte problem.

**Comment by monkoose** [comment]
Nope. Only in help files. They are using some weird formatting, conceals or i dunno, that shifts visible text. So i guess it can't be easy to fix.
I found that bug because i working on some similar plugin, and found this in my implementation. After some tests, i'm more then sure that it is something with neovim `nvim_buf_set_extmark()` that places this hints at the start of the line. Not sure why with Hop there are no hint for `getcurpos()` in mine implementation i have it like so (but i use `vim.fn.searchpos()` for finding locations that in my opinion has less workaround then finding idx with match() and friends). And i can shift with `zl` and `zh` while hints are visible, so if i just hit once `zh` hints will jump to right positions.
Before `zh`
![](https://i.imgur.com/Z1fSpv8.png)
After
![](https://i.imgur.com/OTsYwsp.png)

**Comment by monkoose** [comment]
You can test this with `:lua vim.api.nvim_buf_set_extmark(0, 1, 4708, 7, { virt_text = {{ "we are here", "Error" }}, virt_text_pos = "overlay" })` and `zh` `zl` to the position where `{` in `{expr}` is on the screen and not.

**Comment by phaazon** [comment]
Thanks a lot!

**Comment by phaazon** [comment]
Is this still a thing? I’m going to close because of the stall issue, I don’t reproduce anymore and more has been done lately regarding unicode support in Hop. Thank you.
