### ISSUE TITLE
Greying out of Spell* and LspDiagnostics* highlight groups

### ISSUE THREAD

**Issue by jghauser** [phaazon/hop.nvim#99]
It would be great if the various spelling and lspdiagnostics highlight groups got greyed out just like other text (or simply removed as they're not relevant for jumps). These highlight groups stand out a lot when everything else is dimmed and distract from the jump targets.

![20210621_15h34m08s_grim](https://user-images.githubusercontent.com/10319377/122770862-67e5b700-d295-11eb-89c4-53019e6551d4.jpeg)

I think this should affect the following highlight groups:

- SpellBad 
- SpellCap 
- SpellLocal
- SpellRare
- LspDiagnosticsDefaultError      
- LspDiagnosticsDefaultWarning    
- LspDiagnosticsDefaultInformation
- LspDiagnosticsDefaultHint       
- LspDiagnosticsUnderlineError      
- LspDiagnosticsUnderlineWarning    
- LspDiagnosticsUnderlineInformation
- LspDiagnosticsUnderlineHint

**Comment by phaazon** [comment]
It is likely to be a extmark / virtual text priority thing. Someone made a PR that I need to review in deeper details but that should fix that.

**Comment by jghauser** [comment]
Great, looking forward to it!

**Comment by jghauser** [comment]
This works now and probably has for a while!
